/**
 * Comprehensive tests for ArrayDecoder - Python-TypeScript Compatibility
 *
 * This test suite verifies that TypeScript can correctly decode all encoding
 * modes used by the Python luxar.encoding package:
 * - Broadcasting: Uniform values stored once and replicated
 * - LUT Encoding: ≤256 unique values stored as indices + lookup table
 * - Quantization: uint8/uint16 → float conversion with bounds
 * - Array References: Deduplication via xxhash64
 * - Mixed Encoding: Multiple modes in same scene
 * - 4D Data: nD slicing with time dimension
 *
 * Test datasets are generated by Python script:
 * packages/luxar-viewer/tests/fixtures/generate_test_data.py
 */

import { describe, it, expect } from 'vitest';
import { ArrayDecoder, ArrayRefRegistry } from '../data/array-decoder';
import type { ArrayMetadata } from '../data/array-decoder';
import * as zarr from 'zarrita';
import { FileSystemStore } from '@zarrita/storage';
import * as path from 'path';
import { fileURLToPath } from 'url';

// Get the directory name for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Path to test fixtures
const FIXTURES_DIR = path.resolve(__dirname, '../../tests/fixtures');

/**
 * Helper to load array with attributes from a zarr dataset
 *
 * Uses FileSystemStore for Node.js filesystem access
 * Returns rootLoc for array_ref resolution
 */
async function loadArrayWithAttrs(
  datasetName: string,
  arrayPath: string
): Promise<{
  array: zarr.Array<zarr.DataType, zarr.Readable>;
  attrs: ArrayMetadata;
  rootLoc: zarr.Location<zarr.Readable>;
}> {
  const storePath = path.join(FIXTURES_DIR, datasetName);

  // Create filesystem store for Node.js (not FetchStore - that's for HTTP)
  const rawStore = new FileSystemStore(storePath);
  const store = await zarr.tryWithConsolidated(rawStore);
  const rootLoc = zarr.root(store);

  // Navigate to the array using resolve
  const arrayLoc = rootLoc.resolve(arrayPath);
  const array = await zarr.open(arrayLoc, { kind: 'array' });

  const attrs = array.attrs as unknown as ArrayMetadata;
  return { array, attrs, rootLoc };
}

describe('ArrayDecoder - Python Compatibility Tests', () => {
  describe('Broadcasting Encoding', () => {
    it('should decode broadcasted colors (1, 3) → (1000, 3)', async () => {
      // TODO: Blosc decompression error in numcodecs: "Cannot pass non-string to std::string"
      // This is a known issue with the blosc library bindings in Node.js
      const { array, attrs } = await loadArrayWithAttrs('test_broadcasting.zarr', 'points/colors');

      // Verify metadata indicates broadcasting (nested under "encoding")
      // NOTE: n_elements is the stored array size (1), NOT the target count (1000)
      expect(attrs.encoding?.n_elements).toBe(1);
      expect(attrs.encoding?.name).toBe('broadcasted');
      expect(ArrayDecoder.isEncoded(attrs)).toBe(true);

      // Decode
      const decoder = new ArrayDecoder(new ArrayRefRegistry());
      const decoded = await decoder.decode(array, attrs, 1000);

      // Verify shape: should be replicated to (1000, 3) → 3000 elements
      expect(decoded.length).toBe(1000 * 3);

      // Verify all points have the same color (uniform)
      const firstColor = [decoded[0], decoded[1], decoded[2]];
      for (let i = 0; i < 1000; i++) {
        const offset = i * 3;
        expect(decoded[offset]).toBeCloseTo(firstColor[0], 5);
        expect(decoded[offset + 1]).toBeCloseTo(firstColor[1], 5);
        expect(decoded[offset + 2]).toBeCloseTo(firstColor[2], 5);
      }

      // Verify expected uniform color: [1.0, 0.5, 0.25] (from generate_test_data.py)
      expect(firstColor[0]).toBeCloseTo(1.0, 5);
      expect(firstColor[1]).toBeCloseTo(0.5, 5);
      expect(firstColor[2]).toBeCloseTo(0.25, 5);
    });

    it('should decode broadcasted radii (1,) → (1000,)', async () => {
      // TODO: Blosc decompression error in numcodecs: "Cannot pass non-string to std::string"
      const { array, attrs } = await loadArrayWithAttrs('test_broadcasting.zarr', 'points/radii');

      // Verify metadata (nested under "encoding")
      // NOTE: n_elements is the stored array size (1), NOT the target count (1000)
      expect(attrs.encoding?.n_elements).toBe(1);
      expect(attrs.encoding?.name).toBe('broadcasted');
      expect(ArrayDecoder.isEncoded(attrs)).toBe(true);

      // Decode
      const decoder = new ArrayDecoder(new ArrayRefRegistry());
      const decoded = await decoder.decode(array, attrs, 1000);

      // Verify shape
      expect(decoded.length).toBe(1000);

      // Verify all radii are the same (uniform)
      const firstRadius = decoded[0];
      for (let i = 0; i < 1000; i++) {
        expect(decoded[i]).toBeCloseTo(firstRadius, 5);
      }

      // Verify expected uniform radius: 0.5 (from generate_test_data.py)
      expect(firstRadius).toBeCloseTo(0.5, 5);
    });

    it('should detect non-broadcasted positions as not encoded', async () => {
      // Now works with float32 (float16_allowed=False for TypeScript compatibility)
      // Test fixture: {"encoding": {"name": "float32"}}
      const { attrs } = await loadArrayWithAttrs('test_broadcasting.zarr', 'points/positions');

      // Positions should NOT be encoded (each point has unique position)
      expect(ArrayDecoder.isEncoded(attrs)).toBe(false);
      expect(attrs.encoding?.n_elements).toBeUndefined();
    });
  });

  describe('LUT Encoding', () => {
    it('should decode LUT-encoded colors with 10 unique values', async () => {
      // TODO: Blosc decompression error in numcodecs: "Cannot pass non-string to std::string"
      const { array, attrs } = await loadArrayWithAttrs('test_lut.zarr', 'points/colors');

      // Verify metadata indicates LUT encoding (nested under "encoding")
      // NOTE: Python generates specific names like "lut_uint8", not just "lut"
      expect(attrs.encoding?.name).toBe('lut_uint8');
      expect(attrs.encoding?.lut).toBeDefined();
      expect(ArrayDecoder.isEncoded(attrs)).toBe(true);

      // Decode
      const decoder = new ArrayDecoder(new ArrayRefRegistry());
      const decoded = await decoder.decode(array, attrs, 1000);

      // Verify shape: 1000 points × 3 channels = 3000 elements
      expect(decoded.length).toBe(1000 * 3);

      // Count unique colors (should be exactly 10)
      const uniqueColors = new Set<string>();
      for (let i = 0; i < 1000; i++) {
        const offset = i * 3;
        const colorKey = `${decoded[offset]},${decoded[offset + 1]},${decoded[offset + 2]}`;
        uniqueColors.add(colorKey);
      }

      expect(uniqueColors.size).toBe(10);

      // Verify that decoded colors match expected palette (from generate_test_data.py)
      const expectedColors = [
        [1.0, 0.0, 0.0], // Red
        [0.0, 1.0, 0.0], // Green
        [0.0, 0.0, 1.0], // Blue
        [1.0, 1.0, 0.0], // Yellow
        [1.0, 0.0, 1.0], // Magenta
        [0.0, 1.0, 1.0], // Cyan
        [1.0, 0.5, 0.0], // Orange
        [0.5, 0.0, 1.0], // Purple
        [0.0, 0.5, 0.5], // Teal
        [0.5, 0.5, 0.5], // Gray
      ];

      // Verify all decoded colors are from the palette
      for (let i = 0; i < 1000; i++) {
        const offset = i * 3;
        const color = [decoded[offset], decoded[offset + 1], decoded[offset + 2]];

        const matchesPalette = expectedColors.some(
          (expected) =>
            Math.abs(color[0] - expected[0]) < 0.01 &&
            Math.abs(color[1] - expected[1]) < 0.01 &&
            Math.abs(color[2] - expected[2]) < 0.01
        );

        expect(matchesPalette).toBe(true);
      }
    });
  });

  describe('Quantization Encoding', () => {
    it('should dequantize colors from uint8 to float32', async () => {
      // TODO: Blosc decompression error in numcodecs: "Cannot pass non-string to std::string"
      const { array, attrs } = await loadArrayWithAttrs('test_quantization.zarr', 'points/colors');

      // Verify metadata indicates quantization (nested under "encoding")
      // NOTE: rgb_uint8 has implicit bounds [0, 1], so bounds field may be absent
      expect(attrs.encoding?.name).toBe('rgb_uint8');
      expect(ArrayDecoder.isEncoded(attrs)).toBe(true);

      // Decode
      const decoder = new ArrayDecoder(new ArrayRefRegistry());
      const decoded = await decoder.decode(array, attrs, 1000);

      // Verify shape
      expect(decoded.length).toBe(1000 * 3);

      // Verify all colors are in expected range [0, 1]
      for (let i = 0; i < decoded.length; i++) {
        expect(decoded[i]).toBeGreaterThanOrEqual(0);
        expect(decoded[i]).toBeLessThanOrEqual(1);
      }

      // Verify precision: uint8 quantization should have ~1/255 precision
      // Check that values are not all identical (should vary)
      const uniqueValues = new Set(Array.from(decoded).map((v) => v.toFixed(3)));
      expect(uniqueValues.size).toBeGreaterThan(10); // Should have many distinct values
    });

    it('should load radii in float32 (not quantized)', async () => {
      // Now works with float32 (float16_allowed=False for TypeScript compatibility)
      // Python generates: {"encoding": {"name": "float32"}} for radii
      const { array, attrs } = await loadArrayWithAttrs('test_quantization.zarr', 'points/radii');

      // Verify metadata (nested under "encoding")
      expect(attrs.encoding?.name).toBe('float32');
      expect(ArrayDecoder.isEncoded(attrs)).toBe(false); // float32 is direct storage

      // Decode
      const decoder = new ArrayDecoder(new ArrayRefRegistry());
      const decoded = await decoder.decode(array, attrs, 1000);

      // Verify shape
      expect(decoded.length).toBe(1000);

      // Verify all radii are in expected range [0.1, 2.0]
      for (let i = 0; i < decoded.length; i++) {
        expect(decoded[i]).toBeGreaterThanOrEqual(0.1);
        expect(decoded[i]).toBeLessThanOrEqual(2.0);
      }

      // Verify that radii vary (not all the same)
      const uniqueRadii = new Set(Array.from(decoded).map((v) => v.toFixed(3)));
      expect(uniqueRadii.size).toBeGreaterThan(10);
    });
  });

  describe('Array Reference Deduplication', () => {
    it('should resolve array_ref to target array', async () => {
      // points1/colors is the ORIGINAL (rgb_uint8 encoding)
      // points2/colors is the REFERENCE (array_ref encoding pointing to points1/colors)
      const { array: array1, attrs: attrs1, rootLoc } = await loadArrayWithAttrs(
        'test_array_refs.zarr',
        'points1/colors'
      );
      const { array: array2, attrs: attrs2 } = await loadArrayWithAttrs(
        'test_array_refs.zarr',
        'points2/colors'
      );

      // Verify points1/colors is the original (rgb_uint8, no target)
      expect(attrs1.encoding?.name).toBe('rgb_uint8');
      expect(attrs1.encoding?.target).toBeUndefined();
      expect(ArrayDecoder.isEncoded(attrs1)).toBe(true);

      // Verify points2/colors is an array_ref to points1/colors
      expect(attrs2.encoding?.name).toBe('array_ref');
      expect(attrs2.encoding?.target).toBe('points1/colors');
      expect(attrs2.encoding?.hash).toBeDefined();
      expect(ArrayDecoder.isEncoded(attrs2)).toBe(true);

      // Create shared registry
      const registry = new ArrayRefRegistry();
      const decoder = new ArrayDecoder(registry);

      // Decode both arrays - pass rootLoc for array_ref resolution
      const decoded1 = await decoder.decode(array1, attrs1, 500, rootLoc);
      const decoded2 = await decoder.decode(array2, attrs2, 500, rootLoc);

      // Verify shapes
      expect(decoded1.length).toBe(500 * 3);
      expect(decoded2.length).toBe(500 * 3);

      // Verify both decoded arrays are identical (array_ref resolves to same data)
      for (let i = 0; i < decoded1.length; i++) {
        expect(decoded1[i]).toBeCloseTo(decoded2[i], 5);
      }
    });

    it('should use cached array when decoding array_ref twice', async () => {
      // Load points2/colors which is an array_ref to points1/colors
      const { array: array2, attrs: attrs2, rootLoc } = await loadArrayWithAttrs(
        'test_array_refs.zarr',
        'points2/colors'
      );

      // Verify this is an array_ref
      expect(attrs2.encoding?.name).toBe('array_ref');
      expect(attrs2.encoding?.hash).toBeDefined();

      // Create shared registry
      const registry = new ArrayRefRegistry();
      const decoder = new ArrayDecoder(registry);

      // First decode - should load from target path and cache
      const decoded1 = await decoder.decode(array2, attrs2, 500, rootLoc);
      expect(decoded1.length).toBe(500 * 3);

      // Verify registry now has the cached array
      const hash = attrs2.encoding?.hash!;
      expect(registry.has(hash)).toBe(true);
      const cachedArray = registry.get(hash);
      expect(cachedArray).toBeDefined();

      // Second decode - should hit cache (returns same array instance)
      const decoded2 = await decoder.decode(array2, attrs2, 500, rootLoc);

      // Verify cache hit (same array instance from registry)
      expect(decoded2).toBe(cachedArray);
      expect(decoded2.length).toBe(decoded1.length);
    });
  });

  describe('Mixed Encoding Modes', () => {
    it('should handle multiple encoding modes in same scene', async () => {
      // TODO: Blosc decompression error in numcodecs: "Cannot pass non-string to std::string"
      // Load all three point clouds with different encoding modes
      const uniform = await loadArrayWithAttrs('test_mixed.zarr', 'uniform/colors');
      const lut = await loadArrayWithAttrs('test_mixed.zarr', 'lut/colors');
      const direct = await loadArrayWithAttrs('test_mixed.zarr', 'direct/colors');

      // Verify encoding modes (nested under "encoding")
      expect(uniform.attrs.encoding?.name).toBe('broadcasted'); // Broadcasting
      expect(lut.attrs.encoding?.name).toBe('lut_uint8'); // LUT (specific name)
      expect(ArrayDecoder.isEncoded(direct.attrs)).toBe(false); // Direct (no encoding)

      // Create decoder
      const decoder = new ArrayDecoder(new ArrayRefRegistry());

      // Decode all three
      const decodedUniform = await decoder.decode(uniform.array, uniform.attrs, 500);
      const decodedLUT = await decoder.decode(lut.array, lut.attrs, 500);
      const decodedDirect = await decoder.decode(direct.array, direct.attrs, 500);

      // Verify shapes
      expect(decodedUniform.length).toBe(500 * 3);
      expect(decodedLUT.length).toBe(500 * 3);
      expect(decodedDirect.length).toBe(500 * 3);

      // Verify uniform colors are all the same
      const firstUniformColor = [decodedUniform[0], decodedUniform[1], decodedUniform[2]];
      for (let i = 0; i < 500; i++) {
        const offset = i * 3;
        expect(decodedUniform[offset]).toBeCloseTo(firstUniformColor[0], 5);
        expect(decodedUniform[offset + 1]).toBeCloseTo(firstUniformColor[1], 5);
        expect(decodedUniform[offset + 2]).toBeCloseTo(firstUniformColor[2], 5);
      }

      // Verify LUT has only 2 unique colors (from generate_test_data.py)
      const lutColors = new Set<string>();
      for (let i = 0; i < 500; i++) {
        const offset = i * 3;
        const key = `${decodedLUT[offset]},${decodedLUT[offset + 1]},${decodedLUT[offset + 2]}`;
        lutColors.add(key);
      }
      expect(lutColors.size).toBe(2);

      // Verify direct colors vary (not uniform, not LUT)
      const directColors = new Set<string>();
      for (let i = 0; i < 500; i++) {
        const offset = i * 3;
        const key = `${decodedDirect[offset].toFixed(3)},${decodedDirect[offset + 1].toFixed(3)},${decodedDirect[offset + 2].toFixed(3)}`;
        directColors.add(key);
      }
      expect(directColors.size).toBeGreaterThan(10); // Should have many unique colors
    });
  });

  describe('4D nD Data', () => {
    it('should load 4D positions with time dimension', async () => {
      // Now works with float32 (float16_allowed=False for TypeScript compatibility)
      const { array, attrs } = await loadArrayWithAttrs('test_4d.zarr', 'points/positions');

      // 4D data: 500 points × 10 time steps = 5000 total points
      // Each point has 4 dimensions (time, x, y, z)
      // Total elements: 5000 × 4 = 20,000

      // Load raw data
      const decoder = new ArrayDecoder(new ArrayRefRegistry());
      const decoded = await decoder.decode(array, attrs);

      // Verify shape: 5000 points × 4 dimensions
      expect(decoded.length).toBe(5000 * 4);

      // Verify time dimension values are in range [0, 9]
      const timeValues = new Set<number>();
      for (let i = 0; i < 5000; i++) {
        const offset = i * 4;
        const time = decoded[offset]; // Time is first dimension
        timeValues.add(time);

        expect(time).toBeGreaterThanOrEqual(0);
        expect(time).toBeLessThanOrEqual(9);
      }

      // Verify we have exactly 10 time steps
      expect(timeValues.size).toBe(10);

      // Verify time values are discrete integers
      timeValues.forEach((time) => {
        expect(Number.isInteger(time)).toBe(true);
      });
    });

    it('should load 4D colors that vary with time', async () => {
      // TODO: Blosc decompression error in numcodecs: "Cannot pass non-string to std::string"
      const { array, attrs } = await loadArrayWithAttrs('test_4d.zarr', 'points/colors');

      // Load colors
      const decoder = new ArrayDecoder(new ArrayRefRegistry());
      const decoded = await decoder.decode(array, attrs, 5000);

      // Verify shape: 5000 points × 3 channels
      expect(decoded.length).toBe(5000 * 3);

      // Verify all colors are valid RGB values
      for (let i = 0; i < decoded.length; i++) {
        expect(decoded[i]).toBeGreaterThanOrEqual(0);
        expect(decoded[i]).toBeLessThanOrEqual(1);
      }

      // Verify colors vary (not all the same)
      const uniqueColors = new Set<string>();
      for (let i = 0; i < 5000; i++) {
        const offset = i * 3;
        const key = `${decoded[offset].toFixed(2)},${decoded[offset + 1].toFixed(2)},${decoded[offset + 2].toFixed(2)}`;
        uniqueColors.add(key);
      }

      // Should have multiple unique colors (one per time step at minimum)
      expect(uniqueColors.size).toBeGreaterThanOrEqual(10);
    });
  });

  describe('Error Handling', () => {
    it('should handle direct mode (no encoding)', async () => {
      // Now works with float32 (float16_allowed=False for TypeScript compatibility)
      const { array, attrs } = await loadArrayWithAttrs(
        'test_broadcasting.zarr',
        'points/positions'
      );

      // Positions should be direct mode (no encoding)
      expect(ArrayDecoder.isEncoded(attrs)).toBe(false);

      // Should decode without issues
      const decoder = new ArrayDecoder(new ArrayRefRegistry());
      const decoded = await decoder.decode(array, attrs);

      // Verify shape: 1000 points × 3 dimensions
      expect(decoded.length).toBe(1000 * 3);
    });

    it('should handle missing array_ref in registry', async () => {
      // Create fake attrs with non-existent array_ref (nested under "encoding")
      const fakeAttrs: ArrayMetadata = {
        encoding: {
          target: 'some/target/path',
          hash: 'nonexistent-hash-12345678',
        },
      };

      const decoder = new ArrayDecoder(new ArrayRefRegistry());

      // Should throw error when trying to decode non-existent ref
      await expect(async () => await decoder.decode(null as any, fakeAttrs, 100)).rejects.toThrow();
    });
  });

  describe('Performance and Edge Cases', () => {
    it('should handle large broadcasted arrays efficiently', async () => {
      // TODO: Blosc decompression error in numcodecs: "Cannot pass non-string to std::string"
      const { array, attrs } = await loadArrayWithAttrs('test_broadcasting.zarr', 'points/colors');

      const decoder = new ArrayDecoder(new ArrayRefRegistry());

      // Measure decode time
      const startTime = performance.now();
      const decoded = await decoder.decode(array, attrs, 1000);
      const endTime = performance.now();

      // Should complete quickly (< 100ms for 1000 points)
      expect(endTime - startTime).toBeLessThan(100);

      // Verify correctness
      expect(decoded.length).toBe(3000);
    });

    it.skip('should handle empty arrays gracefully', async () => {
      // TODO: Mocking zarr.Array interface is too complex - test via integration tests instead
      // Create fake empty array metadata (nested under "encoding")
      const emptyAttrs: ArrayMetadata = {
        encoding: {
          name: 'broadcasted',
          n_elements: 1, // Stored size (not target)
        },
        shape: [1, 3],
      };

      const decoder = new ArrayDecoder(new ArrayRefRegistry());

      // Create a mock empty array - needs full zarr.Array interface
      const emptyData = new Float32Array(3); // Shape (1, 3) but broadcasting to 0 elements
      const mockArray = {
        shape: [1, 3],
        chunks: [1, 3],
        dtype: '<f4',
        attrs: {},
        get: async () => ({
          data: emptyData,
          shape: [1, 3],
          stride: [3, 1],
        }),
      };

      const decoded = await decoder.decode(mockArray as any, emptyAttrs, 0);

      // Should return empty array
      expect(decoded.length).toBe(0);
    });
  });
});
