/**
 * E2E for click actions on a picked element (issue #1917).
 *
 * Exercises the whole pipeline the unit tests can only stub:
 *
 *   mouse motion → settle scheduler → performPick → label loader →
 *   picked-element cache → pointerup → resolved URL → a real browser tab
 *
 * Two firsts for this suite, both deliberate: no spec has ever asserted a
 * popup, and none has ever exercised a `contextmenu` on the canvas. The popup
 * assertion follows the shape `recording-panel.spec.ts` uses for downloads —
 * start waiting BEFORE the gesture, await after.
 *
 * Dataset: `test_linked_points.luxar.zarr` — a single point at the world
 * origin carrying `link` + `copy`, generated by
 * `tests/fixtures/generate_test_data.py::generate_linked_points_test`.
 */

import { test, expect, type Page } from './fixtures';
import { waitForLuxarReady, waitForPointsLoaded, assertNoConsoleErrors } from './helpers';

const DATASET =
  'http://localhost:9000/packages/luxar-viewer/tests/fixtures/test_linked_points.luxar.zarr';

/** Must match `LINKED_LABEL` / `LINKED_URL_PREFIX` in the fixture generator. */
const LABEL = 'Linked point';
/** The space in the label is percent-encoded — that is the point of the space. */
const EXPECTED_URL = 'https://example.org/entry/Linked%20point';

/** Viewport centre of the canvas, where the fixture's single point sits. */
async function canvasCentre(page: Page): Promise<{ x: number; y: number }> {
  return await page.evaluate(() => {
    const canvas = (
      window as unknown as { __luxarDebug: { renderer: { domElement: HTMLCanvasElement } } }
    ).__luxarDebug.renderer.domElement;
    const r = canvas.getBoundingClientRect();
    return { x: r.left + r.width / 2, y: r.top + r.height / 2 };
  });
}

/**
 * Park the cursor away, then move onto the target and let the pick settle.
 *
 * The settle scheduler only fires once the cursor has been STILL for
 * HOVER_SETTLE_MS (120 ms), so a single move straight to the target from
 * wherever the cursor happened to be is not enough — the same two-step
 * `hover-tooltip.spec.ts` uses.
 */
async function hoverAndSettle(page: Page, at: { x: number; y: number }): Promise<void> {
  await page.mouse.move(at.x + 140, at.y + 140);
  await page.waitForTimeout(250);
  await page.mouse.move(at.x, at.y);
  await expect(page.locator('[data-overlay-name="__hover_text"]')).toHaveText(LABEL, {
    timeout: 10000,
  });
}

test.describe('element actions — click to open a link', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(`/?src=${DATASET}&debug`);
    await waitForLuxarReady(page);
    await waitForPointsLoaded(page);
  });

  test.afterEach(async ({ page }) => {
    await assertNoConsoleErrors(page);
  });

  test('hovering the element shows its label and a pointer cursor', async ({ page }) => {
    const centre = await canvasCentre(page);
    await hoverAndSettle(page, centre);

    const overlay = page.locator('[data-overlay-name="__hover_text"]');
    await expect(overlay).toHaveText(LABEL, { timeout: 10000 });

    // The affordance: without it a link is invisible until clicked by accident.
    const cursor = await page.evaluate(() => {
      const canvas = (
        window as unknown as { __luxarDebug: { renderer: { domElement: HTMLCanvasElement } } }
      ).__luxarDebug.renderer.domElement;
      return canvas.style.cursor;
    });
    expect(cursor).toBe('pointer');
  });

  test('left-clicking opens the resolved URL in a new tab', async ({ page, context }) => {
    const centre = await canvasCentre(page);
    await hoverAndSettle(page, centre);

    const popupPromise = context.waitForEvent('page', { timeout: 10000 });
    await page.mouse.down();
    await page.mouse.up();
    const popup = await popupPromise;

    // Percent-encoded, proving the value went through encodeURIComponent
    // rather than being interpolated raw into the template.
    expect(popup.url()).toBe(EXPECTED_URL);
    await popup.close();
  });

  test('dragging across the element opens nothing', async ({ page, context }) => {
    // The gesture that must NOT navigate: a camera orbit/pan that happens to
    // start on a linked element.
    const centre = await canvasCentre(page);
    await hoverAndSettle(page, centre);

    let opened = false;
    context.on('page', () => {
      opened = true;
    });

    await page.mouse.down();
    await page.mouse.move(centre.x + 60, centre.y + 30, { steps: 8 });
    await page.mouse.up();
    await page.waitForTimeout(500);

    expect(opened).toBe(false);
  });

  test('?noLinks suppresses navigation and the pointer cursor', async ({ page, context }) => {
    await page.goto(`/?src=${DATASET}&debug&noLinks`);
    await waitForLuxarReady(page);
    await waitForPointsLoaded(page);

    const centre = await canvasCentre(page);
    await hoverAndSettle(page, centre);

    let opened = false;
    context.on('page', () => {
      opened = true;
    });

    await page.mouse.down();
    await page.mouse.up();
    await page.waitForTimeout(500);

    expect(opened).toBe(false);
    const cursor = await page.evaluate(() => {
      const canvas = (
        window as unknown as { __luxarDebug: { renderer: { domElement: HTMLCanvasElement } } }
      ).__luxarDebug.renderer.domElement;
      return canvas.style.cursor;
    });
    expect(cursor).not.toBe('pointer');
  });
});

test.describe('element actions — right-click menu', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(`/?src=${DATASET}&debug`);
    await waitForLuxarReady(page);
    await waitForPointsLoaded(page);
  });

  test.afterEach(async ({ page }) => {
    await assertNoConsoleErrors(page);
  });

  test('opens the shared menu with all three items', async ({ page }) => {
    const centre = await canvasCentre(page);
    await hoverAndSettle(page, centre);

    await page.mouse.down({ button: 'right' });
    await page.mouse.up({ button: 'right' });

    const menu = page.locator('.luxar-context-menu');
    await expect(menu).toBeVisible({ timeout: 5000 });
    await expect(menu).toContainText('Copy "id=Linked point"');
    await expect(menu).toContainText('Open link in new tab');
    await expect(menu).toContainText('Copy link address');
  });

  test('right-dragging opens no menu', async ({ page }) => {
    const centre = await canvasCentre(page);
    await hoverAndSettle(page, centre);

    await page.mouse.down({ button: 'right' });
    await page.mouse.move(centre.x + 60, centre.y + 30, { steps: 8 });
    await page.mouse.up({ button: 'right' });
    await page.waitForTimeout(400);

    await expect(page.locator('.luxar-context-menu')).toHaveCount(0);
  });

  test('Escape dismisses the menu', async ({ page }) => {
    const centre = await canvasCentre(page);
    await hoverAndSettle(page, centre);
    await page.mouse.down({ button: 'right' });
    await page.mouse.up({ button: 'right' });
    await expect(page.locator('.luxar-context-menu')).toBeVisible({ timeout: 5000 });

    await page.keyboard.press('Escape');
    await expect(page.locator('.luxar-context-menu')).toHaveCount(0);
  });
});

test.describe('element actions — embedder events', () => {
  test('element-click fires with the element and the resolved link', async ({ page, context }) => {
    await page.goto(`/?src=${DATASET}&debug`);
    await waitForLuxarReady(page);
    await waitForPointsLoaded(page);

    await page.evaluate(() => {
      const w = window as unknown as {
        __luxarDebug: { app: { on: (e: string, cb: (p: unknown) => void) => void } };
        __clicks: unknown[];
      };
      w.__clicks = [];
      w.__luxarDebug.app.on('element-click', (p) => w.__clicks.push(p));
    });

    const centre = await canvasCentre(page);
    await hoverAndSettle(page, centre);

    const popupPromise = context.waitForEvent('page', { timeout: 10000 });
    await page.mouse.down();
    await page.mouse.up();
    await (await popupPromise).close();

    const clicks = await page.evaluate(
      () => (window as unknown as { __clicks: unknown[] }).__clicks
    );
    expect(clicks).toHaveLength(1);
    expect(clicks[0]).toMatchObject({
      nodeName: '/linked_points',
      hitNodeName: '/linked_points',
      button: 0,
      link: EXPECTED_URL,
    });
    // NOT pinned to a literal: the writer spatially reorders points, so the
    // centre point's on-disk row is whatever the Hilbert curve puts it at.
    // That the link still resolves to the right label is itself the evidence
    // that the label CSR tracked the same permutation.
    const index = (clicks[0] as { elementIndex: number }).elementIndex;
    expect(Number.isInteger(index)).toBe(true);
    expect(index).toBeGreaterThanOrEqual(0);
    expect(index).toBeLessThan(5);
  });
});
