/**
 * Lines & GSplats Geometry Type E2E Tests
 *
 * Verifies that Lines and GSplats geometry types render correctly in the browser.
 * These are first-class geometry types alongside Points, but had NO E2E coverage.
 *
 * Test fixtures: test_lines.zarr, test_gsplats.zarr
 * (auto-generated by packages/luxar-viewer/tests/fixtures/generate_test_data.py)
 */

import { test, expect } from './fixtures';
import { waitForLuxarReady, assertNoConsoleErrors, getWebGLErrors } from './helpers';

const FIXTURES_BASE = 'http://localhost:9000/packages/luxar-viewer/tests/fixtures';

const FIXTURES = {
  lines: `${FIXTURES_BASE}/test_lines.zarr`,
  gsplats: `${FIXTURES_BASE}/test_gsplats.zarr`,
};

test.describe('Lines Geometry Rendering', () => {
  test('should load and render Lines without errors', async ({ page }) => {
    await page.goto(`/?src=${FIXTURES.lines}&debug`);
    await waitForLuxarReady(page);

    // No console errors during loading
    await assertNoConsoleErrors(page);

    // No WebGL errors
    const webglErrors = await getWebGLErrors(page);
    expect(webglErrors.length).toBe(0);
  });

  test('should have Lines mesh in scene with correct attributes', async ({ page }) => {
    await page.goto(`/?src=${FIXTURES.lines}&debug`);
    await waitForLuxarReady(page);

    const linesInfo = await page.evaluate(() => {
      const debug = (window as any).__luxarDebug;
      const results: any[] = [];

      debug.scene.traverse((obj: any) => {
        if (obj.userData?.nodeType === 'lines') {
          const geom = obj.geometry;
          results.push({
            name: obj.name,
            nodeType: obj.userData.nodeType,
            isInstancedGeometry: geom?.isInstancedBufferGeometry ?? false,
            hasPosition: !!geom?.attributes?.position,
            materialType: obj.material?.type,
            visible: obj.visible,
          });
        }
      });

      return results;
    });

    expect(linesInfo.length).toBeGreaterThan(0);

    const line = linesInfo[0];
    expect(line.nodeType).toBe('lines');
    expect(line.isInstancedGeometry).toBe(true);
    expect(line.visible).toBe(true);
    expect(line.materialType).toBe('ShaderMaterial');
  });
});

test.describe('GSplats Geometry Rendering', () => {
  test('should load and render GSplats without errors', async ({ page }) => {
    await page.goto(`/?src=${FIXTURES.gsplats}&debug`);
    await waitForLuxarReady(page);

    // No console errors during loading
    await assertNoConsoleErrors(page);

    // No WebGL errors
    const webglErrors = await getWebGLErrors(page);
    expect(webglErrors.length).toBe(0);
  });

  test('should have GSplats mesh in scene with correct attributes', async ({ page }) => {
    await page.goto(`/?src=${FIXTURES.gsplats}&debug`);
    await waitForLuxarReady(page);

    const gsplatsInfo = await page.evaluate(() => {
      const debug = (window as any).__luxarDebug;
      const results: any[] = [];

      debug.scene.traverse((obj: any) => {
        if (obj.userData?.nodeType === 'gsplats') {
          const geom = obj.geometry;
          results.push({
            name: obj.name,
            nodeType: obj.userData.nodeType,
            isInstancedGeometry: geom?.isInstancedBufferGeometry ?? false,
            hasPosition: !!geom?.attributes?.position,
            materialType: obj.material?.type,
            visible: obj.visible,
          });
        }
      });

      return results;
    });

    expect(gsplatsInfo.length).toBeGreaterThan(0);

    const splat = gsplatsInfo[0];
    expect(splat.nodeType).toBe('gsplats');
    expect(splat.isInstancedGeometry).toBe(true);
    expect(splat.visible).toBe(true);
    expect(splat.materialType).toBe('ShaderMaterial');
  });
});
