/**
 * E2E hover-tooltip behaviour for the GPU picking system.
 *
 * Sibling to `hover-overlay.spec.ts`: that file isolates the
 * `OverlayManager.updateHoverContent` DOM mutation by bypassing
 * picking entirely. THIS spec exercises the full pipeline:
 *
 *   mouse motion → settle scheduler → performPick → label loader →
 *   OverlayManager.updateHoverContent → DOM
 *
 * Dataset: `test_labelled_points.luxar.zarr` — a tiny fixture with 8
 * labelled points generated by
 * `tests/fixtures/generate_test_data.py::generate_labelled_points_test`.
 * The default auto-injected `__hover_text` overlay is included by the
 * Python scene compiler whenever `has_labels=True`.
 *
 * Uses `PickingSystem.getDiagnostics()` to read the settle-scheduler
 * timestamps without reaching into private fields.
 */

import { test, expect, type Page } from './fixtures';
import { waitForLuxarReady, waitForPointsLoaded, assertNoConsoleErrors } from './helpers';

const DATASET =
  'http://localhost:9000/packages/luxar-viewer/tests/fixtures/test_labelled_points.luxar.zarr';

interface PickingDiagnostics {
  lastPickFiredTime: number;
  lastMouseMoveTime: number;
  lastDirtyTime: number;
  registeredNodeCount: number;
  suppressed: boolean;
}

async function readDiagnostics(page: Page): Promise<PickingDiagnostics> {
  return await page.evaluate(() => {
    const debug = (
      window as unknown as {
        __luxarDebug: {
          app: { pickingSystem?: { getDiagnostics: () => PickingDiagnostics } };
        };
      }
    ).__luxarDebug;
    const ps = debug?.app?.pickingSystem;
    if (!ps) throw new Error('PickingSystem not initialized — fixture has no labels?');
    return ps.getDiagnostics();
  });
}

/**
 * Return the centre of the WebGL canvas in viewport coordinates. The
 * fixture's 8 points are arranged symmetrically around the world
 * origin; the viewer's default camera framing puts the cluster around
 * the canvas centre, so the central pixel is near at least one point.
 * That's enough for the picking-system's 5×5 readback window to hit
 * a real element.
 */
async function getCanvasCentre(page: Page): Promise<{ x: number; y: number }> {
  return await page.evaluate(() => {
    const debug = (
      window as unknown as {
        __luxarDebug: { renderer: { domElement: HTMLCanvasElement } };
      }
    ).__luxarDebug;
    const canvas = debug.renderer.domElement;
    const rect = canvas.getBoundingClientRect();
    return {
      x: rect.left + rect.width / 2,
      y: rect.top + rect.height / 2,
    };
  });
}

test.describe('Hover-tooltip end-to-end (GPU picking + settle + overlay)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(`/?src=${DATASET}&debug`);
    await waitForLuxarReady(page);
    await waitForPointsLoaded(page);
  });

  test.afterEach(async ({ page }) => {
    await assertNoConsoleErrors(page);
  });

  test('PickingSystem initializes for a labelled fixture and exposes diagnostics', async ({
    page,
  }) => {
    const d = await readDiagnostics(page);
    expect(d.registeredNodeCount).toBeGreaterThanOrEqual(1);
    expect(d.suppressed).toBe(false);
    expect(d.lastPickFiredTime).toBe(0); // never picked
  });

  test('idle baseline: hover overlay element exists at opacity 0', async ({ page }) => {
    const overlay = page.locator('[data-overlay-name="__hover_text"]');
    await expect(overlay).toHaveCount(1);
    await expect(overlay).toHaveCSS('opacity', '0');
  });

  test('cursor settles on a point → settle scheduler fires a pick within 250 ms', async ({
    page,
  }) => {
    // Move to a known canvas position and let everything settle from the load.
    await page.mouse.move(10, 10);
    await page.waitForTimeout(200);
    const before = await readDiagnostics(page);

    // Move to a point's projected position and stay still
    const target = await getCanvasCentre(page);
    await page.mouse.move(target.x, target.y);
    await page.waitForTimeout(250); // HOVER_SETTLE_MS + margin

    const after = await readDiagnostics(page);
    expect(after.lastPickFiredTime).toBeGreaterThan(before.lastPickFiredTime);
  });

  test('cursor in continuous motion never triggers a pick', async ({ page }) => {
    // Sweep the cursor across the canvas without ever pausing. Drive the
    // sweep from inside the browser so the gaps between dispatched
    // mousemove events are bounded by `setTimeout(0)` (a few ms) rather
    // than by Playwright IPC + Node-side `waitForTimeout` (~40 ms each,
    // and >150 ms under CI load). The previous implementation used per-
    // iteration `page.mouse.move` + `page.waitForTimeout(40)` and was
    // flaky on slow machines because individual gaps could exceed
    // HOVER_SETTLE_MS, allowing the settle loop to fire a pick.
    const start = await readDiagnostics(page);
    const target = await getCanvasCentre(page);

    await page.evaluate(
      async ([tx, ty]) => {
        const canvas = document.querySelector('canvas');
        if (!canvas) throw new Error('canvas missing');
        for (let i = 0; i < 60; i++) {
          const dx = (i % 7) - 3;
          const dy = (Math.floor(i / 7) % 7) - 3;
          const ev = new MouseEvent('mousemove', {
            clientX: tx + dx * 4,
            clientY: ty + dy * 4,
            bubbles: true,
            cancelable: true,
          });
          canvas.dispatchEvent(ev);
          // ~16 ms between moves keeps the gap well below the 120 ms
          // settle window even under heavy worker load.
          await new Promise((r) => setTimeout(r, 16));
        }
      },
      [target.x, target.y] as const
    );

    const after = await readDiagnostics(page);
    expect(after.lastPickFiredTime).toBe(start.lastPickFiredTime);
  });
});
