/**
 * E2E hover-tooltip behaviour for the GPU picking system.
 *
 * Sibling to `hover-overlay.spec.ts`: that file isolates the
 * `OverlayManager.updateHoverContent` DOM mutation by bypassing
 * picking entirely. THIS spec exercises the full pipeline:
 *
 *   mouse motion → settle scheduler → performPick → label loader →
 *   OverlayManager.updateHoverContent → DOM
 *
 * Dataset: `test_labelled_points.luxar.zarr` — a tiny fixture with 8
 * labelled points generated by
 * `tests/fixtures/generate_test_data.py::generate_labelled_points_test`.
 * The default auto-injected `__hover_text` overlay is included by the
 * Python scene compiler whenever `has_labels=True`.
 *
 * Uses `PickingSystem.getDiagnostics()` to read the settle-scheduler
 * timestamps without reaching into private fields.
 */

import { test, expect, type Page } from './fixtures';
import { waitForLuxarReady, waitForPointsLoaded, assertNoConsoleErrors } from './helpers';
import { HOVER_SETTLE_MS } from '../../rendering/picking/picking-system/settle-loop';

const DATASET =
  'http://localhost:9000/packages/luxar-viewer/tests/fixtures/test_labelled_points.luxar.zarr';

/**
 * Partitioned sibling of `DATASET` — the same labelled-points shape, but
 * authored with `add_points(partition=...)` so the node is a `kind=partition`
 * wrapper over four `part_<i>` leaves. The label CSR lives on the leaves;
 * the wrapper is a bare group. See
 * `generate_test_data.py::generate_labelled_partitioned_points_test`.
 */
const PARTITIONED_DATASET =
  'http://localhost:9000/packages/luxar-viewer/tests/fixtures/test_labelled_partitioned_points.luxar.zarr';

/** Label of the fixture's single isolated hover target, at the world origin. */
const MARKER_LABEL = 'Origin marker';

interface PickingDiagnostics {
  lastPickFiredTime: number;
  lastMouseMoveTime: number;
  lastDirtyTime: number;
  registeredNodeCount: number;
  suppressed: boolean;
}

async function readDiagnostics(page: Page): Promise<PickingDiagnostics> {
  return await page.evaluate(() => {
    const debug = (
      window as unknown as {
        __luxarDebug: {
          app: { pickingSystem?: { getDiagnostics: () => PickingDiagnostics } };
        };
      }
    ).__luxarDebug;
    const ps = debug?.app?.pickingSystem;
    if (!ps) throw new Error('PickingSystem not initialized — fixture has no labels?');
    return ps.getDiagnostics();
  });
}

/**
 * Return the centre of the WebGL canvas in viewport coordinates. The
 * fixture's 8 points are arranged symmetrically around the world
 * origin; the viewer's default camera framing puts the cluster around
 * the canvas centre, so the central pixel is near at least one point.
 * That's enough for the picking-system's 5×5 readback window to hit
 * a real element.
 */
async function getCanvasCentre(page: Page): Promise<{ x: number; y: number }> {
  return await page.evaluate(() => {
    const debug = (
      window as unknown as {
        __luxarDebug: { renderer: { domElement: HTMLCanvasElement } };
      }
    ).__luxarDebug;
    const canvas = debug.renderer.domElement;
    const rect = canvas.getBoundingClientRect();
    return {
      x: rect.left + rect.width / 2,
      y: rect.top + rect.height / 2,
    };
  });
}

/**
 * Project a WORLD-space point to viewport coordinates through the live
 * camera. Stronger than `getCanvasCentre` for an assertion about *which*
 * element was hit: it does not assume the default framing centres the point
 * of interest, so a change to auto-framing turns into a miss at a known
 * position rather than a silently different element.
 *
 * `THREE` is not on `window`, so the only handle on `Vector3` is an existing
 * instance — `camera.position` — which is cloned and overwritten.
 */
async function projectWorldPoint(
  page: Page,
  world: [number, number, number]
): Promise<{ x: number; y: number }> {
  return await page.evaluate((w) => {
    const debug = (
      window as unknown as {
        __luxarDebug: {
          camera: {
            position: {
              clone: () => {
                set: (x: number, y: number, z: number) => { project: (c: unknown) => unknown };
              };
            };
          };
          renderer: { domElement: HTMLCanvasElement };
        };
      }
    ).__luxarDebug;
    const camera = debug.camera;
    const ndc = camera.position.clone().set(w[0], w[1], w[2]).project(camera) as {
      x: number;
      y: number;
    };
    const rect = debug.renderer.domElement.getBoundingClientRect();
    return {
      x: rect.left + ((ndc.x + 1) / 2) * rect.width,
      y: rect.top + ((1 - ndc.y) / 2) * rect.height,
    };
  }, world);
}

test.describe('Hover-tooltip end-to-end (GPU picking + settle + overlay)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(`/?src=${DATASET}&debug`);
    await waitForLuxarReady(page);
    await waitForPointsLoaded(page);
  });

  test.afterEach(async ({ page }) => {
    await assertNoConsoleErrors(page);
  });

  test('PickingSystem initializes for a labelled fixture and exposes diagnostics', async ({
    page,
  }) => {
    const d = await readDiagnostics(page);
    expect(d.registeredNodeCount).toBeGreaterThanOrEqual(1);
    expect(d.suppressed).toBe(false);
    expect(d.lastPickFiredTime).toBe(0); // never picked
  });

  test('idle baseline: hover overlay element exists at opacity 0', async ({ page }) => {
    const overlay = page.locator('[data-overlay-name="__hover_text"]');
    await expect(overlay).toHaveCount(1);
    await expect(overlay).toHaveCSS('opacity', '0');
  });

  test('cursor settles on a point → settle scheduler fires a pick within 250 ms', async ({
    page,
  }) => {
    // Move to a known canvas position and let everything settle from the load.
    await page.mouse.move(10, 10);
    await page.waitForTimeout(200);
    const before = await readDiagnostics(page);

    // Move to a point's projected position and stay still
    const target = await getCanvasCentre(page);
    await page.mouse.move(target.x, target.y);
    await page.waitForTimeout(250); // HOVER_SETTLE_MS + margin

    const after = await readDiagnostics(page);
    expect(after.lastPickFiredTime).toBeGreaterThan(before.lastPickFiredTime);
  });

  test('cursor in continuous motion never triggers a pick', async ({ page }) => {
    // Drain any camera-settle pick armed by the tail of scene loading before
    // defining the sweep's assertion window.
    await page.mouse.move(10, 10);
    await page.waitForTimeout(HOVER_SETTLE_MS + 80);

    // Sweep the cursor across the canvas without ever pausing. Drive the
    // sweep from inside the browser so the gaps between dispatched events
    // avoid Playwright IPC + Node-side `waitForTimeout` (~40 ms each,
    // and >150 ms under CI load). The previous implementation used per-
    // iteration `page.mouse.move` + `page.waitForTimeout(40)` and was
    // flaky on slow machines because individual gaps could exceed
    // HOVER_SETTLE_MS, allowing the settle loop to fire a pick.
    const sweep = await page.evaluate(async () => {
      const debug = (
        window as unknown as {
          __luxarDebug: {
            app: { pickingSystem?: { getDiagnostics: () => PickingDiagnostics } };
            renderer: { domElement: HTMLCanvasElement };
          };
        }
      ).__luxarDebug;
      const pickingSystem = debug?.app?.pickingSystem;
      if (!pickingSystem) throw new Error('PickingSystem not initialized — fixture has no labels?');
      const canvas = debug.renderer.domElement;
      const rect = canvas.getBoundingClientRect();
      const tx = rect.left + rect.width / 2;
      const ty = rect.top + rect.height / 2;
      const startPickFiredTime = pickingSystem.getDiagnostics().lastPickFiredTime;
      let previousMoveTime = 0;
      let maxMoveGap = 0;

      for (let i = 0; i < 60; i++) {
        const moveTime = performance.now();
        if (previousMoveTime !== 0) {
          maxMoveGap = Math.max(maxMoveGap, moveTime - previousMoveTime);
        }
        previousMoveTime = moveTime;

        const dx = (i % 7) - 3;
        const dy = (Math.floor(i / 7) % 7) - 3;
        const ev = new MouseEvent('mousemove', {
          clientX: tx + dx * 4,
          clientY: ty + dy * 4,
          bubbles: true,
          cancelable: true,
        });
        canvas.dispatchEvent(ev);
        if (i < 59) {
          await new Promise((resolve) => setTimeout(resolve, 16));
        }
      }

      return {
        startPickFiredTime,
        endPickFiredTime: pickingSystem.getDiagnostics().lastPickFiredTime,
        maxMoveGap,
      };
    });

    expect(sweep.maxMoveGap).toBeLessThan(HOVER_SETTLE_MS);
    expect(sweep.endPickFiredTime).toBe(sweep.startPickFiredTime);
  });
});

/**
 * Regression coverage for #1415, and the only test in the suite that runs the
 * hover pipeline against a `kind=partition` layer.
 *
 * The cases above use a FLAT node, where the handler's reported path and its
 * lookup path are the same string — so they cannot observe the bug at all.
 * Here the CSR lives on `labelled_parts/part_<i>` while the layer the viewer
 * reports is `labelled_parts`; querying the wrapper (the pre-fix behaviour)
 * finds no `label_offsets` / `label_bytes`, logs an info line, caches an empty
 * label array, and leaves the tooltip blank forever after. Asserting the
 * tooltip's exact TEXT — not merely that a pick fired — is what makes that
 * silent failure visible.
 */
test.describe('Hover-tooltip on a kind=partition layer (#1415)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(`/?src=${PARTITIONED_DATASET}&debug`);
    await waitForLuxarReady(page);
    await waitForPointsLoaded(page);
  });

  test.afterEach(async ({ page }) => {
    await assertNoConsoleErrors(page);
  });

  test('hovering the marker resolves its label from the part_<i> leaf', async ({ page }) => {
    const overlay = page.locator('[data-overlay-name="__hover_text"]');
    await expect(overlay).toHaveCount(1);

    // Park the cursor away from the marker first, so the move onto it is a
    // genuine settle (the scheduler only fires after the cursor stops).
    const target = await projectWorldPoint(page, [0, 0, 0]);
    await page.mouse.move(target.x + 120, target.y + 120);
    await page.waitForTimeout(250);

    await page.mouse.move(target.x, target.y);

    // The exact authored label of the one point at the world origin. Every
    // other point in the fixture sits at |x| >= 6, so a hit on anything else
    // reads "Cluster point N" and fails loudly rather than passing vacuously.
    await expect(overlay).toHaveText(MARKER_LABEL, { timeout: 10000 });
    await expect(overlay).toHaveCSS('opacity', '1');
  });

  test('the selection event reports the wrapper as nodeName and the leaf as hitNodeName', async ({
    page,
  }) => {
    // The public embedder payload's partition contract (#1415): `nodeName` is
    // the user-facing layer, `hitNodeName` is the node `elementIndex` is
    // actually local to. Under this fixture the two MUST differ.
    await page.evaluate(() => {
      const w = window as unknown as {
        __luxarDebug: { app: { on: (e: string, cb: (s: unknown) => void) => void } };
        __selections: unknown[];
      };
      w.__selections = [];
      w.__luxarDebug.app.on('selection', (sel) => {
        if (sel) w.__selections.push(sel);
      });
    });

    const target = await projectWorldPoint(page, [0, 0, 0]);
    await page.mouse.move(target.x + 120, target.y + 120);
    await page.waitForTimeout(250);
    await page.mouse.move(target.x, target.y);

    await expect
      .poll(
        async () =>
          await page.evaluate(
            () => (window as unknown as { __selections: unknown[] }).__selections.length
          ),
        { timeout: 10000 }
      )
      .toBeGreaterThan(0);

    const sel = (await page.evaluate(() => {
      const sels = (
        window as unknown as {
          __selections: { nodeName: string; elementIndex: number; hitNodeName: string }[];
        }
      ).__selections;
      return sels[sels.length - 1];
    }))!;

    expect(sel.nodeName).toBe('/labelled_parts');
    expect(sel.hitNodeName).toMatch(/^\/labelled_parts\/part_\d+$/);
    expect(sel.hitNodeName).not.toBe(sel.nodeName);
    expect(sel.elementIndex).toBeGreaterThanOrEqual(0);
  });
});
