/**
 * SliceCache ("S-cache") E2E Tests
 *
 * Verifies the per-slice decoded-geometry cache end to end in a real
 * browser, on a 4D progressive dataset (additive LODs + hidden discrete
 * frame dimension — the configuration the S-cache exists for):
 * - Scrub-back HITS: revisiting frames restores decoded slices from the
 *   cache (including the round-5 departure store: partial ladders are
 *   snapshotted when the view leaves a slice, so fast scrubbing stays warm).
 * - `?noSliceCache` disables ONLY the S-cache (L0/L1/L2 stay wired).
 * - The Data Loading Monitor's Cache tab surfaces the SLICE CACHE section
 *   with live values, collapsible section headers (mouse + keyboard), and
 *   a working per-section Clear action.
 *
 * These behaviors previously had NO E2E coverage (deep-double-check
 * round-5 gap map); unit tests cover the loaders with mocked sub-loaders,
 * but only this spec exercises the real fetch→decode→cache→restore cycle.
 */

import { test, expect } from './fixtures';
import { waitForLuxarReady, waitForDataLoaded, getLuxarState } from './helpers';

test.describe.configure({ timeout: 120000 });

// 4D progressive points: 8 discrete frames × 40K points, 4 additive LODs
// (generated by packages/luxar/examples/progressive_timelapse_example.py).
const DATASET = 'http://localhost:9000/datasets/examples/progressive_timelapse_example.luxar.zarr';
const FRAME_DIM = 3;

/** S-cache stats via the debug interface (null when the cache is disabled). */
async function getSliceStats(page: any): Promise<{
  size: number;
  count: number;
  hits: number;
  misses: number;
} | null> {
  return await page.evaluate(() => {
    const debug = (window as any).__luxarDebug;
    const loader = debug?.getSceneLoader?.()?.getDefaultLoader?.();
    const sc = loader ? (loader as any).sliceCache : null;
    return sc ? sc.getStats() : null;
  });
}

/**
 * Navigate the hidden frame dimension and wait for the load-pass signal
 * (`getState().isLoading`) to settle: frame commit, not additive-ladder drain.
 * A fixed dwell is flaky:
 * rapid navigations coalesce in the SceneLoader's pending queue, so
 * intermediate frames would never get their own load — the S-cache
 * legitimately stores nothing for a frame that was never visited.
 */
async function goToFrame(page: any, frame: number): Promise<void> {
  await page.evaluate(
    ({ dim, f }: { dim: number; f: number }) => {
      (window as any).__luxarDebug.sceneDimsManager.setDimensionValue(dim, f);
    },
    { dim: FRAME_DIM, f: frame }
  );
  await waitForDataLoaded(page, 15000);
  // One extra beat so post-update refinement kicks/stores can land.
  await page.waitForTimeout(250);
}

test.describe('SliceCache (S-cache)', () => {
  test('scrub-back revisits are served from the S-cache (hit count grows, entries stored)', async ({
    page,
  }) => {
    // `&noOpfs` on every load: this spec never asserts the L2 OPFS tier, and
    // automated Chromium's OPFS stalls systemically (10s per op — issue #1645),
    // starving scene readiness past the test budget. The circuit breaker only
    // helps un-flagged real sessions (it still pays ~3 timeouts per fresh page).
    await page.goto(`/?src=${DATASET}&debug&noOpfs`);
    await waitForLuxarReady(page);
    await page.waitForTimeout(1500);

    // Two departures fill the cache (completion stores + departure stores).
    await goToFrame(page, 1);
    await goToFrame(page, 2);
    const afterForward = await getSliceStats(page);
    expect(afterForward).not.toBeNull();
    expect(afterForward!.count).toBeGreaterThan(0); // slices stored

    // Revisit a stored frame: it must produce a cache HIT.
    await goToFrame(page, 1);
    const afterBack = await getSliceStats(page);
    expect(afterBack).not.toBeNull();
    expect(afterBack!.hits).toBeGreaterThan(afterForward!.hits);

    // A revisited frame renders data (the restore path produces geometry).
    const state = await getLuxarState(page);
    expect(state.totalPoints).toBeGreaterThan(0);
  });

  // L2 is off here by `&noOpfs` (see above), so the claim this test can make
  // is that the chunk-cache stack stays WIRED — unlike `?noCache`, which
  // tears it down entirely.
  test('?noSliceCache disables ONLY the S-cache (the chunk-cache stack stays wired)', async ({
    page,
  }) => {
    await page.goto(`/?src=${DATASET}&debug&noSliceCache&noOpfs`);
    await waitForLuxarReady(page);
    await page.waitForTimeout(1000);

    expect(await getSliceStats(page)).toBeNull(); // S-cache not constructed

    // The chunk-cache stack is still wired (unlike ?noCache).
    const cacheStats = await page.evaluate(async () => {
      const debug = (window as any).__luxarDebug;
      return await debug.cache.getStats();
    });
    expect(cacheStats).not.toHaveProperty('error');
    expect(cacheStats.l1).toBeTruthy();
  });

  test('scrubbing with ?noSliceCache still renders every frame (bypass is safe)', async ({
    page,
  }) => {
    await page.goto(`/?src=${DATASET}&debug&noSliceCache&noOpfs`);
    await waitForLuxarReady(page);
    await page.waitForTimeout(1500);

    await goToFrame(page, 2);
    await goToFrame(page, 1);
    const state = await getLuxarState(page);
    expect(state.totalPoints).toBeGreaterThan(0);
  });
});

test.describe('Data Loading Monitor — S-cache section', () => {
  /** Open the expanded monitor on the Cache tab. */
  async function openCacheTab(page: any): Promise<void> {
    await page.keyboard.press('m'); // compact
    await page.waitForTimeout(300);
    await page.keyboard.press('m'); // expanded
    await page.waitForTimeout(500);
    await page.click('[data-action="setTab"][data-tab-id="cache"]');
    await page.waitForTimeout(1200); // let a polling tick patch values
  }

  test('SLICE CACHE section renders with live values and collapse toggles by mouse + keyboard', async ({
    page,
  }) => {
    await page.goto(`/?src=${DATASET}&debug&noOpfs`);
    await waitForLuxarReady(page);
    await page.waitForTimeout(1500);
    // Generate some cache traffic first so values are non-trivial.
    await goToFrame(page, 1);
    await goToFrame(page, 0);

    await openCacheTab(page);

    // Section present, collapsed by default, values live in the summary.
    const section = page.locator('.luxar-cache-section[data-section="slice"]');
    await expect(section).toHaveClass(/luxar-cache-section--collapsed/);
    const summaryValue = await section
      .locator('.luxar-cache-section__summary [data-field="s-size"]')
      .textContent();
    expect(summaryValue?.trim()).toMatch(/B$/); // a formatted byte size

    // Mouse toggle expands to the full card grid; every value renders in
    // BOTH copies (summary + card) with identical text.
    await section.locator('.luxar-cache-section__title').click();
    await expect(section).not.toHaveClass(/luxar-cache-section--collapsed/);
    const copies = await page.$$eval('[data-field="s-hitrate"]', (els) =>
      els.map((e) => e.textContent?.trim())
    );
    expect(copies).toHaveLength(2);
    expect(copies[0]).toBe(copies[1]);

    // Keyboard toggle (headers are role=button + tabindex=0): Enter collapses.
    const header = section.locator('.luxar-cache-section__header');
    await expect(header).toHaveAttribute('role', 'button');
    await expect(header).toHaveAttribute('aria-expanded', 'true');
    await header.focus();
    await page.keyboard.press('Enter');
    await expect(section).toHaveClass(/luxar-cache-section--collapsed/);
    await expect(header).toHaveAttribute('aria-expanded', 'false');
  });

  test('Clear button empties the S-cache without collapsing the section state', async ({
    page,
  }) => {
    await page.goto(`/?src=${DATASET}&debug&noOpfs`);
    await waitForLuxarReady(page);
    await page.waitForTimeout(1500);
    await goToFrame(page, 1);
    await goToFrame(page, 2);

    const before = await getSliceStats(page);
    expect(before!.count).toBeGreaterThan(0);

    await openCacheTab(page);
    const section = page.locator('.luxar-cache-section[data-section="slice"]');
    const collapsedBefore = await section.evaluate((el) =>
      el.classList.contains('luxar-cache-section--collapsed')
    );
    await section.locator('[data-action="clearSlice"]').click();
    await page.waitForTimeout(400);

    const after = await getSliceStats(page);
    expect(after!.count).toBe(0);
    // Clear must not toggle the collapse state (nearest data-action wins).
    const collapsedAfter = await section.evaluate((el) =>
      el.classList.contains('luxar-cache-section--collapsed')
    );
    expect(collapsedAfter).toBe(collapsedBefore);
  });

  test('tab-switch entrance animation is one-shot (marker cleared by live rebuilds)', async ({
    page,
  }) => {
    await page.goto(`/?src=${DATASET}&debug&noOpfs`);
    await waitForLuxarReady(page);
    await page.keyboard.press('m');
    await page.waitForTimeout(300);
    await page.keyboard.press('m');
    await page.waitForTimeout(500);

    // The Insights tab rebuilds its content every polling tick — the
    // one-shot --animate marker must be gone after the first tick, or the
    // entrance fade replays at 10Hz (round-5 finding).
    await page.click('[data-action="setTab"][data-tab-id="insights"]');
    await page.waitForTimeout(1500);
    const stillAnimating = await page.evaluate(() =>
      document
        .querySelector('.luxar-data-monitor__content')
        ?.classList.contains('luxar-data-monitor__content--animate')
    );
    expect(stillAnimating).toBe(false);
  });
});
