/**
 * Standalone .gsplats.zarr bare-node load (Phase 4 end-to-end proof).
 *
 * A v3.x standalone .gsplats.zarr is a *detached gsplats leaf node*, not a
 * scene. Opening it via ?src= must:
 *   1. dispatch the file root as a gsplats leaf (not an empty 'scene'
 *      container) — proven by getState().totalGSplats > 0;
 *   2. auto-frame it — the fixture's splat cluster is offset well away from
 *      the origin, so a working frame-on-load is the only way the data lands
 *      on-screen (non-black canvas). A broken frame leaves the camera at the
 *      default origin and the offset cluster falls off-screen (black);
 *   3. render without shader errors.
 *
 * The fixture (test_standalone_gsplats.gsplats.zarr) is generated by
 * tests/fixtures/generate_test_data.py — run `pnpm test:generate-fixtures`.
 */

import { test, expect } from './fixtures';
import {
  waitForLuxarReady,
  waitForRenderStable,
  assertNoShaderErrors,
  getElementPixelStats,
  renderOnce,
} from './helpers';

const FIXTURES_BASE = 'http://localhost:9000/packages/luxar-viewer/tests/fixtures';
const STANDALONE = `${FIXTURES_BASE}/test_standalone_gsplats.gsplats.zarr`;

test.describe('Standalone .gsplats.zarr bare-node load', () => {
  test('a bare gsplats leaf root loads as a gsplats node (not an empty scene)', async ({
    page,
  }) => {
    await page.goto(`/?src=${STANDALONE}&debug`);
    await waitForLuxarReady(page);
    await waitForRenderStable(page);

    const state = await page.evaluate(() => {
      const debug = (window as { __luxarDebug?: { getState?: () => unknown } }).__luxarDebug;
      return debug?.getState ? debug.getState() : null;
    });
    expect(state, 'expected __luxarDebug.getState() to be available').not.toBeNull();
    const s = state as {
      totalGSplats: number;
      gsplatMeshes: Array<{ name: string; splatCount: number; visible: boolean }>;
    };
    // The bare leaf root must have been dispatched + loaded as a gsplats node.
    expect(s.totalGSplats, 'standalone bare node should load its splats').toBe(40);
    expect(s.gsplatMeshes.length).toBeGreaterThan(0);
    expect(s.gsplatMeshes.some((m) => m.splatCount === 40 && m.visible)).toBe(true);
  });

  test('the offset cluster is auto-framed on load (non-black canvas)', async ({ page }) => {
    await page.goto(`/?src=${STANDALONE}&debug&dpr=1`);
    await waitForLuxarReady(page);
    await waitForRenderStable(page);

    // No manual camera move: the cluster (offset ~[12,8,5] from origin) is only
    // visible if the initial auto-frame used the node's position_bounds.
    const stats = await getElementPixelStats(page, 'canvas#app', 10, 'framebuffer');
    expect(
      stats.nonBlackPixels,
      `Expected the auto-framed standalone cluster to be visible; stats=${JSON.stringify(stats)}`
    ).toBeGreaterThan(0);

    const hidden = await page.evaluate(() => {
      let count = 0;
      (window as any).__luxarDebug.scene.traverse((object: any) => {
        if (object.userData?.nodeType === 'gsplats') {
          object.visible = false;
          count++;
        }
      });
      return count;
    });
    expect(hidden, 'the blank-frame control must hide the standalone GSplat node').toBeGreaterThan(
      0
    );
    await renderOnce(page);
    const blankStats = await getElementPixelStats(page, 'canvas#app', 10, 'framebuffer');
    expect(
      blankStats.nonBlackPixels,
      `Hidden standalone GSplat node still produced visible pixels; stats=${JSON.stringify(blankStats)}`
    ).toBeLessThan(10);
  });

  test('renders without shader errors', async ({ page }) => {
    await page.goto(`/?src=${STANDALONE}&debug`);
    await waitForLuxarReady(page);
    await waitForRenderStable(page);
    await assertNoShaderErrors(page);
  });
});
