"""GPU benchmark profile management for multi-GPU systems.

Stores and aggregates benchmark results in a YAML file at
``~/.luxar/gpu_profiles.yaml``. Each GPU (keyed by its canonical name)
can have multiple benchmark runs; a summary is recomputed on every append
using average throughput and conservative (min) OOM boundaries.

This module is consumed by ``luxar gsplat slurm-fit`` to auto-select tile
sizes and estimate wall times.
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

PROFILE_PATH = Path.home() / ".luxar" / "gpu_profiles.yaml"
SCHEMA_VERSION = 2


# ---------------------------------------------------------------------------
# NoAliasDumper — avoids YAML anchors/aliases for readability
# ---------------------------------------------------------------------------


class _NoAliasDumper(yaml.SafeDumper):
    def ignore_aliases(self, data: Any) -> bool:
        return True


# ---------------------------------------------------------------------------
# Load / Save
# ---------------------------------------------------------------------------


def _ensure_dir(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def load_profiles(path: Path = PROFILE_PATH) -> Dict[str, Any]:
    """Load the multi-GPU profile YAML.

    Returns an empty structure if the file does not exist.
    On first access, auto-migrates a v1 profile if found.
    """
    if not path.exists():
        # Try auto-migration from v1 (only if not already migrated)
        old_path = path.parent / "gpu_benchmark_profile.yaml"
        backup_path = old_path.with_suffix(".yaml.bak")
        if old_path.exists() and not backup_path.exists():
            migrate_v1_profile(old_path, path)
        if path.exists():
            return load_profiles(path)
        return {"schema_version": SCHEMA_VERSION, "gpus": {}}

    try:
        with open(path) as f:
            data = yaml.safe_load(f)
    except (yaml.YAMLError, UnicodeDecodeError):
        # Corrupted file — return empty and let the next save fix it
        return {"schema_version": SCHEMA_VERSION, "gpus": {}}

    if data is None:
        return {"schema_version": SCHEMA_VERSION, "gpus": {}}

    # Validate schema version
    version = data.get("schema_version", 1)
    if version != SCHEMA_VERSION:
        raise ValueError(
            f"GPU profile schema version {version} is not supported "
            f"(expected {SCHEMA_VERSION}). Delete {path} and re-run "
            f"`luxar gsplat benchmark`."
        )

    return dict(data)


def save_profiles(profiles: Dict[str, Any], path: Path = PROFILE_PATH) -> None:
    """Write the multi-GPU profile YAML atomically."""
    _ensure_dir(path)
    profiles["schema_version"] = SCHEMA_VERSION

    tmp_path = path.with_suffix(".yaml.tmp")
    with open(tmp_path, "w") as f:
        f.write(
            "# GPU Benchmark Profiles — auto-generated by luxar gsplat benchmark\n"
            "# Multi-GPU registry with per-GPU benchmark runs and aggregated summaries.\n"
            f"# Last updated: {datetime.datetime.now(datetime.timezone.utc).isoformat()}\n"
            "#\n"
            "# Re-generate with: luxar gsplat benchmark\n\n"
        )
        yaml.dump(
            profiles,
            f,
            Dumper=_NoAliasDumper,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
    tmp_path.replace(path)


# ---------------------------------------------------------------------------
# Append a benchmark run
# ---------------------------------------------------------------------------


def append_run(
    gpu_name: str,
    run_data: Dict[str, Any],
    gpu_info: Dict[str, Any],
    path: Path = PROFILE_PATH,
) -> None:
    """Append a benchmark run for a GPU and recompute the summary.

    Args:
        gpu_name: Canonical GPU name (e.g. ``"NVIDIA GeForce RTX 3090 Ti"``).
        run_data: Dict with keys ``throughput``, ``oom_boundaries``,
            ``splat_sweep`` (optional), ``recommendations``, ``timestamp``,
            ``cuda_version``, ``pytorch_version``, ``free_memory_gb``.
        gpu_info: Dict with keys ``total_memory_gb``, ``compute_capability``,
            ``sm_count``.
        path: Profile YAML path.
    """
    profiles = load_profiles(path)
    gpus = profiles.setdefault("gpus", {})

    if gpu_name not in gpus:
        gpus[gpu_name] = {
            "info": gpu_info,
            "runs": [],
            "summary": {},
        }

    entry = gpus[gpu_name]
    # Update info in case hardware metadata improved
    entry["info"] = gpu_info
    entry["runs"].append(run_data)
    entry["summary"] = recompute_summary(entry["runs"])

    save_profiles(profiles, path)


# ---------------------------------------------------------------------------
# Summary recomputation
# ---------------------------------------------------------------------------


def recompute_summary(runs: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Recompute aggregated summary from all benchmark runs.

    - Throughput: **average** across runs (more stable).
    - OOM boundaries: **min** across runs (conservative — never recommend
      a size that OOMed even once).
    - Recommendations: derived from averaged throughput.
    """
    if not runs:
        return {}

    summary: Dict[str, Any] = {}

    # --- Aggregate throughput (average across runs) ---
    avg_throughput = _average_throughput(runs)
    if avg_throughput:
        summary["throughput_avg"] = avg_throughput

    # --- Conservative OOM boundaries (min across runs) ---
    oom = _conservative_oom(runs)
    if oom:
        summary["oom_boundaries"] = oom

    # --- Recommendations ---
    recs: Dict[str, Any] = {}

    # Peak 3D throughput from averaged data
    if "3d" in avg_throughput:
        best_gvs = 0.0
        best_entry: Optional[Dict[str, Any]] = None
        for entry in avg_throughput["3d"]:
            if entry.get("oom"):
                continue
            gvs = entry.get("fp32_gvoxel_per_s", 0)
            if gvs > best_gvs:
                best_gvs = gvs
                best_entry = entry
        if best_entry is not None:
            recs["peak_throughput_3d"] = {
                "shape": best_entry["shape"],
                "gvoxel_per_s": round(best_gvs, 1),
                "splats": best_entry["splats"],
            }
            # Store train ms at peak for time estimation
            if best_entry.get("amp_train_ms") is not None:
                recs["amp_train_ms_at_peak"] = best_entry["amp_train_ms"]
            elif best_entry.get("fp32_train_ms") is not None:
                recs["amp_train_ms_at_peak"] = best_entry["fp32_train_ms"]

    # Memory-safe max voxels (from latest run's recommendations if available)
    for run in reversed(runs):
        run_recs = run.get("recommendations", {})
        if "memory_safe_max_voxels_fp32" in run_recs:
            recs["memory_safe_max_voxels_fp32"] = run_recs[
                "memory_safe_max_voxels_fp32"
            ]
            break
    for run in reversed(runs):
        run_recs = run.get("recommendations", {})
        if "memory_safe_max_cube_side_3d" in run_recs:
            recs["memory_safe_max_cube_side_3d"] = run_recs[
                "memory_safe_max_cube_side_3d"
            ]
            break

    if recs:
        summary["recommendations"] = recs

    return summary


def _average_throughput(runs: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Average throughput entries across runs, keyed by label."""
    result: Dict[str, Any] = {}

    for dim_key in ("3d", "2d"):
        # Collect all entries by label
        by_label: Dict[str, List[Dict[str, Any]]] = {}
        for run in runs:
            entries = run.get("throughput", {}).get(dim_key, [])
            for entry in entries:
                label = entry.get("label", "")
                by_label.setdefault(label, []).append(entry)

        if not by_label:
            continue

        averaged = []
        for label, entries in by_label.items():
            avg: Dict[str, Any] = {
                "label": label,
                "shape": entries[0]["shape"],
                "voxels": entries[0]["voxels"],
                "splats": entries[0]["splats"],
            }

            # If any run OOMed for this config, mark as OOM (conservative)
            if any(e.get("oom") for e in entries):
                avg["oom"] = True
                averaged.append(avg)
                continue

            avg["oom"] = False
            # Average numeric fields
            for key in (
                "fp32_ms",
                "fp32_gvoxel_per_s",
                "amp_ms",
                "amp_gvoxel_per_s",
                "fp32_train_ms",
                "amp_train_ms",
            ):
                vals = [e[key] for e in entries if key in e and e[key] is not None]
                if vals:
                    avg[key] = round(sum(vals) / len(vals), 2)

            averaged.append(avg)

        result[dim_key] = averaged

    return result


def _conservative_oom(runs: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Take the most conservative OOM boundaries across runs."""
    result: Dict[str, Any] = {}

    for dim_key in ("3d", "2d"):
        # Collect all OOM boundary entries
        max_ok_voxels: Optional[int] = None
        max_ok_shape: Optional[list] = None
        min_oom_voxels: Optional[int] = None
        min_oom_shape: Optional[list] = None

        for run in runs:
            oom = run.get("oom_boundaries", {}).get(dim_key, {})
            ok_v = oom.get("max_successful_voxels")
            if ok_v is not None:
                if max_ok_voxels is None or ok_v < max_ok_voxels:
                    max_ok_voxels = ok_v
                    max_ok_shape = oom.get("max_successful_shape")

            oom_v = oom.get("min_oom_voxels")
            if oom_v is not None:
                if min_oom_voxels is None or oom_v < min_oom_voxels:
                    min_oom_voxels = oom_v
                    min_oom_shape = oom.get("min_oom_shape")

        entry: Dict[str, Any] = {}
        if max_ok_voxels is not None:
            entry["max_successful_voxels"] = max_ok_voxels
            entry["max_successful_shape"] = max_ok_shape
        if min_oom_voxels is not None:
            entry["min_oom_voxels"] = min_oom_voxels
            entry["min_oom_shape"] = min_oom_shape

        if entry:
            result[dim_key] = entry

    return result


# ---------------------------------------------------------------------------
# Query helpers
# ---------------------------------------------------------------------------


def get_gpu_summary(
    gpu_name: Optional[str] = None,
    gpu_mem: Optional[float] = None,
    path: Path = PROFILE_PATH,
) -> Optional[Dict[str, Any]]:
    """Get the summary for a GPU.

    Args:
        gpu_name: Exact GPU name. If ``None``, tries auto-detection via
            ``torch.cuda``, then falls back to the only profiled GPU.
        gpu_mem: If set and gpu_name is None, pick the profile whose
            ``total_memory_gb`` is closest to this value.
        path: Profile YAML path.

    Returns:
        Summary dict or ``None`` if no matching profile exists.
    """
    profiles = load_profiles(path)
    gpus = profiles.get("gpus", {})

    if not gpus:
        return None

    if gpu_name is not None:
        entry = gpus.get(gpu_name)
        if entry is None:
            return None
        summary: Dict[str, Any] = entry["summary"]
        return summary

    # Auto-detect from current CUDA device
    detected_name = _detect_gpu_name()
    if detected_name and detected_name in gpus:
        detected_summary: Dict[str, Any] = gpus[detected_name]["summary"]
        return detected_summary

    # Match by GPU memory
    if gpu_mem is not None:
        best_name = None
        best_diff = float("inf")
        for name, entry in gpus.items():
            mem = entry.get("info", {}).get("total_memory_gb", 0)
            diff = abs(mem - gpu_mem)
            if diff < best_diff:
                best_diff = diff
                best_name = name
        if best_name:
            mem_summary: Dict[str, Any] = gpus[best_name]["summary"]
            return mem_summary

    # If only one GPU profiled, use it
    if len(gpus) == 1:
        single_summary: Dict[str, Any] = next(iter(gpus.values()))["summary"]
        return single_summary

    # Multiple profiles but no GPU available for auto-detection (e.g. login
    # node) — pick the one with the least memory (conservative).
    if gpus:
        conservative_name = min(
            gpus,
            key=lambda n: gpus[n].get("info", {}).get("total_memory_gb", 0),
        )
        return dict(gpus[conservative_name]["summary"])

    return None


def get_gpu_throughput_table(
    gpu_name: Optional[str] = None,
    path: Path = PROFILE_PATH,
) -> Optional[List[Dict[str, Any]]]:
    """Get the averaged 3D throughput table for a GPU.

    Returns list of throughput entries sorted by voxel count, or None.
    """
    profiles = load_profiles(path)
    gpus = profiles.get("gpus", {})

    # Resolve GPU name
    name = gpu_name
    if name is None:
        name = _detect_gpu_name()
    if name is None and len(gpus) == 1:
        name = next(iter(gpus.keys()))
    if name is None or name not in gpus:
        return None

    summary = gpus[name].get("summary", {})
    table = summary.get("throughput_avg", {}).get("3d", [])
    # Sort by voxel count
    return sorted(table, key=lambda e: e.get("voxels", 0))


def list_profiled_gpus(path: Path = PROFILE_PATH) -> List[str]:
    """List all GPU names that have profiles."""
    profiles = load_profiles(path)
    return list(profiles.get("gpus", {}).keys())


# ---------------------------------------------------------------------------
# V1 migration
# ---------------------------------------------------------------------------


def migrate_v1_profile(
    old_path: Path,
    new_path: Path = PROFILE_PATH,
) -> bool:
    """Migrate old single-GPU profile (v1) to the new multi-GPU format.

    Reads the old YAML, wraps its data as a single run, writes to the new
    location. Renames the old file to ``.bak``.

    Returns:
        True if migration happened, False if old file not found or invalid.
    """
    if not old_path.exists():
        return False

    with open(old_path) as f:
        old_data = yaml.safe_load(f)

    if old_data is None or not isinstance(old_data, dict):
        return False

    gpu_info_raw = old_data.get("gpu", {})
    gpu_name = gpu_info_raw.get("name")
    if not gpu_name:
        return False

    # Build gpu_info (static hardware info)
    gpu_info = {
        k: v
        for k, v in gpu_info_raw.items()
        if k in ("total_memory_gb", "compute_capability", "sm_count")
    }

    # Build run_data (everything else)
    run_data: Dict[str, Any] = {
        "timestamp": old_data.get("timestamp", "unknown"),
        "cuda_version": gpu_info_raw.get("cuda_version", "unknown"),
        "pytorch_version": gpu_info_raw.get("pytorch_version", "unknown"),
        "free_memory_gb": gpu_info_raw.get("free_memory_gb", 0),
        "throughput": old_data.get("throughput", {}),
        "oom_boundaries": old_data.get("oom_boundaries", {}),
        "recommendations": old_data.get("recommendations", {}),
    }
    if "splat_sweep" in old_data:
        run_data["splat_sweep"] = old_data["splat_sweep"]

    # Build new structure
    profiles: Dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "gpus": {
            gpu_name: {
                "info": gpu_info,
                "runs": [run_data],
                "summary": recompute_summary([run_data]),
            }
        },
    }

    save_profiles(profiles, new_path)

    # Rename old file (safe even if .bak already exists)
    backup_path = old_path.with_suffix(".yaml.bak")
    try:
        old_path.rename(backup_path)
    except OSError:
        # .bak may already exist or rename failed — just delete old file
        try:
            old_path.unlink()
        except OSError:
            pass

    return True


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _detect_gpu_name() -> Optional[str]:
    """Detect current GPU name via torch.cuda, or None."""
    try:
        import torch as _torch
    except ImportError:
        return None

    try:
        if _torch.cuda.is_available():
            return _torch.cuda.get_device_properties(0).name
    except (RuntimeError, AssertionError):
        # CUDA initialization or driver errors
        pass
    return None
