/**
 * Media-utility helpers for the recording panel.
 *
 * Pure functions extracted from `ui/recording-panel.ts` so the
 * arithmetic + string-formatting paths are unit-testable without a
 * real `MediaRecorder` or DOM. The browser-coupled
 * {@link getSupportedMimeType} accepts an explicit MediaRecorder-like
 * argument so it can also be tested with a stub.
 *
 * @module ui/recording/media-utilities
 */

/** Quality presets for video recording. */
export type VideoQuality = 'low' | 'medium' | 'high' | 'max';

/**
 * Bits-per-pixel multipliers for single-pass VP9 encoding. The default
 * MediaRecorder bitrate (~2.5 Mbps) is far too low for HD content.
 */
const BPP_BY_QUALITY: Record<VideoQuality, number> = {
  low: 0.04, // ~2.5 Mbps at 1080p30 (comparable to default)
  medium: 0.08, // ~5 Mbps at 1080p30
  high: 0.15, // ~9.3 Mbps at 1080p30 — good quality
  max: 0.3, // ~18.7 Mbps at 1080p30 — near-lossless
};

/**
 * Compute the recommended video bitrate (bits per second) for a given
 * canvas size, FPS, and quality preset.
 *
 * `width × height × fps × bpp`, rounded.
 */
export function computeVideoBitrate(
  width: number,
  height: number,
  fps: number,
  quality: VideoQuality
): number {
  const bpp = BPP_BY_QUALITY[quality] ?? BPP_BY_QUALITY.high;
  return Math.round(width * height * fps * bpp);
}

/**
 * Minimal contract we need from `MediaRecorder` to probe codec
 * support — just the static `isTypeSupported(string)` method.
 */
export interface MediaRecorderLike {
  isTypeSupported(type: string): boolean;
}

/**
 * Return the highest-quality WebM codec MediaRecorder can record with,
 * or `null` if MediaRecorder is unavailable / no codec is supported.
 *
 * MediaRecorder only supports WebM with VP9 or VP8 — H.264/H.265 are
 * NOT valid WebM codecs (the videoCodec option there only applies to
 * the offline mediabunny path, not real-time recording).
 *
 * Pass an explicit `recorder` for testing; default uses the global.
 */
export function getSupportedMimeType(
  recorder: MediaRecorderLike | undefined = typeof MediaRecorder !== 'undefined'
    ? (MediaRecorder as unknown as MediaRecorderLike)
    : undefined
): string | null {
  if (!recorder) return null;
  const candidates = ['video/webm;codecs=vp9', 'video/webm;codecs=vp8', 'video/webm'];
  for (const type of candidates) {
    if (recorder.isTypeSupported(type)) {
      return type;
    }
  }
  return null;
}

/** Padding-2 helper used by {@link generateTimestampSuffix}. */
function pad2(n: number): string {
  return n.toString().padStart(2, '0');
}

/**
 * Format a Date as `YYYY-MM-DD-hhmmss`. Pure given an explicit Date.
 */
export function generateTimestampSuffix(now: Date): string {
  return (
    `${now.getFullYear()}-${pad2(now.getMonth() + 1)}-${pad2(now.getDate())}-` +
    `${pad2(now.getHours())}${pad2(now.getMinutes())}${pad2(now.getSeconds())}`
  );
}

/**
 * Build a Luxar capture filename with the given extension and a timestamp
 * suffix. Defaults `now` to `new Date()` for production callers; tests
 * can pin a specific Date.
 */
export function generateFilename(ext: string, now: Date = new Date()): string {
  return `luxar-capture-${generateTimestampSuffix(now)}.${ext}`;
}

/**
 * Generate a shell script with ffmpeg commands to encode a frame
 * sequence. The HDR path is appended only for EXR (since 8-bit PNG/JPEG
 * sequences don't carry HDR data).
 *
 * Pure: no I/O, deterministic given the inputs.
 */
export function generateFfmpegScript(fps: number, frameCount: number, ext = 'exr'): string {
  const duration = (frameCount / fps).toFixed(1);
  const isHDRFormat = ext === 'exr';
  const inputPattern = `frame_%06d.${ext}`;
  return `#!/bin/bash
# Luxar Image Sequence Encoder
# ${frameCount} ${ext.toUpperCase()} frames at ${fps} FPS (${duration}s)
# Generated by Luxar Viewer — https://github.com/royerlab/luxar
#
# Requirements: ffmpeg
# Usage: chmod +x encode_video.sh && ./encode_video.sh

set -e
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# --- MP4 (H.265, high quality) ---
echo "Encoding MP4 (H.265)..."
ffmpeg -y -framerate ${fps} -i '${inputPattern}' \\
  -c:v libx265 -preset slow -crf 18 \\
  -pix_fmt yuv420p \\
  -movflags +faststart \\
  "turntable.mp4"
echo "  -> turntable.mp4"

# --- MP4 (H.264, widely compatible) ---
# Uncomment if H.265 is not supported by your player:
# echo "Encoding MP4 (H.264)..."
# ffmpeg -y -framerate ${fps} -i '${inputPattern}' \\
#   -c:v libx264 -preset slow -crf 18 \\
#   -pix_fmt yuv420p \\
#   -movflags +faststart \\
#   "turntable_h264.mp4"
# echo "  -> turntable_h264.mp4"
${
  isHDRFormat
    ? `
# --- HDR MP4 (H.265, 10-bit PQ/BT.2020) ---
echo "Encoding HDR MP4 (H.265 10-bit)..."
ffmpeg -y -framerate ${fps} -i '${inputPattern}' \\
  -c:v libx265 -preset slow -crf 18 \\
  -pix_fmt yuv420p10le \\
  -color_primaries bt2020 -color_trc smpte2084 -colorspace bt2020nc \\
  -movflags +faststart \\
  "turntable_hdr.mp4"
echo "  -> turntable_hdr.mp4"
`
    : ''
}

echo "Done!"
`;
}

/**
 * Anchor offset (same semantics as CSS `transform: translate`). Pure.
 */
export type AnchorName =
  | 'top-left'
  | 'top-center'
  | 'top-right'
  | 'center-left'
  | 'center'
  | 'center-right'
  | 'bottom-left'
  | 'bottom-center'
  | 'bottom-right';

export function anchorOffset(
  anchor: AnchorName | string,
  width: number,
  height: number
): [number, number] {
  switch (anchor) {
    case 'top-left':
      return [0, 0];
    case 'top-center':
      return [-width / 2, 0];
    case 'top-right':
      return [-width, 0];
    case 'center-left':
      return [0, -height / 2];
    case 'center':
      return [-width / 2, -height / 2];
    case 'center-right':
      return [-width, -height / 2];
    case 'bottom-left':
      return [0, -height];
    case 'bottom-center':
      return [-width / 2, -height];
    case 'bottom-right':
      return [-width, -height];
    default:
      return [0, 0];
  }
}
