/**
 * TS ↔ Python parity of the LOD metrics, case by case.
 *
 * `luxar.io.lod_screening` ports `lod-selector-math.ts` and claims agreement
 * to 1e-9. The committed fixture is GENERATED by the Python metrics
 * (`packages/luxar/src/luxar/io/tests/test_lod_metric_parity.py`, which also
 * fails when the fixture goes stale); this suite recomputes every case with
 * the viewer's own metric. It also pins the two shared constants the Python
 * mirror hard-codes: the hysteresis default and `FILL_FACTOR`.
 */
import * as THREE from 'three';
import { describe, expect, it } from 'vitest';

import { config } from '../../../config';
import { FILL_FACTOR } from '../../../scene/lod-group-registry';
import {
  pickChildWithHysteresis,
  projectBoxAreaFraction,
  projectBoxDiagonalPx,
} from '../../../scene/lod-selector-math';
import fixture from './fixtures/lod-metric-parity.json';

type Num = number | 'inf';
type FixtureCamera = (typeof fixture.cases)[number]['camera'];

const num = (v: Num): number => (v === 'inf' ? Number.POSITIVE_INFINITY : v);

/** Relative 1e-9 (absolute near zero), infinities exactly. */
function expectParity(got: number, want: Num, what: string): void {
  const expected = num(want);
  if (!Number.isFinite(expected)) {
    expect(got, what).toBe(expected);
    return;
  }
  expect(Math.abs(got - expected), what).toBeLessThanOrEqual(
    1e-9 * Math.max(1, Math.abs(expected))
  );
}

function camera(c: FixtureCamera): THREE.Camera {
  const cam =
    c.type === 'perspective'
      ? new THREE.PerspectiveCamera(c.fov, c.aspect, c.near, c.far)
      : new THREE.OrthographicCamera(c.left, c.right, c.top, c.bottom, c.near, c.far);
  cam.position.fromArray(c.position);
  cam.updateMatrixWorld();
  cam.updateProjectionMatrix();
  return cam;
}

describe('LOD metric parity with luxar.io.lod_screening', () => {
  it('shares the hysteresis default and FILL_FACTOR with the Python mirror', () => {
    expect(config.lod.hysteresisRatio).toBe(fixture.hysteresis_ratio);
    expect(FILL_FACTOR).toBe(fixture.fill_factor);
  });

  it('covers perspective, near-clipped, saturated and orthographic cases', () => {
    const types = new Set(fixture.cases.map((c) => c.camera.type));
    expect(types).toEqual(new Set(['perspective', 'orthographic']));
    expect(fixture.cases.some((c) => c.area_fraction === 'inf')).toBe(true);
    expect(fixture.cases.some((c) => c.name.includes('near-clipped'))).toBe(true);
  });

  for (const c of fixture.cases) {
    it(`matches Python on: ${c.name}`, () => {
      const cam = camera(c.camera);
      // The Python matrices are THREE's: P·V·world built here equals the fixture's.
      const world = new THREE.Matrix4().fromArray(c.world);
      const built = new THREE.Matrix4()
        .multiplyMatrices(cam.projectionMatrix, cam.matrixWorldInverse)
        .multiply(world);
      built.elements.forEach((v, i) => expectParity(v, c.box_to_clip[i], `box_to_clip[${i}]`));

      const boxToClip = new THREE.Matrix4().fromArray(c.box_to_clip);
      const box = {
        min: { x: c.box.min[0], y: c.box.min[1], z: c.box.min[2] },
        max: { x: c.box.max[0], y: c.box.max[1], z: c.box.max[2] },
      };
      const [width, height] = c.viewport;
      const diagonal = projectBoxDiagonalPx(box, cam, { width, height }, boxToClip);
      expectParity(projectBoxAreaFraction(box, cam, boxToClip), c.area_fraction as Num, 'area');
      expectParity(diagonal, c.diagonal_px as Num, 'diagonal');
      expectParity(
        diagonal / (FILL_FACTOR * Math.min(width, height)),
        c.legacy_coverage as Num,
        'legacy coverage'
      );
    });
  }

  it('picks the same level, hysteresis included, at the default ratio', () => {
    for (const p of fixture.picks) {
      expect(
        pickChildWithHysteresis(p.thresholds, p.current, num(p.metric as Num)),
        JSON.stringify(p)
      ).toBe(p.expected);
    }
  });
});
