onlyBuiltDependencies:
  - esbuild

overrides:
  postcss@<8.5.10: '>=8.5.10'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  minimatch@<3.1.4: '>=3.1.4 <4.0.0'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7 <10.0.0'
  brace-expansion@<1.1.13: '>=1.1.13 <2.0.0'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3 <3.0.0'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4 <5.0.0'
  flatted@<3.4.2: '>=3.4.2 <4.0.0'
  ajv@<6.14.0: '>=6.14.0 <7.0.0'
  diff@>=4.0.0 <4.0.4: '>=4.0.4 <5.0.0'
