#!/usr/bin/env python3
"""Self-Contained Demo: HuRI — the Human Reference Interactome.

Visualize the first proteome-scale map of direct human protein-protein
interactions (Luck et al. 2020, Nature): ~8k proteins as Points and
~50k binary Y2H interactions as Lines, laid out in 3D purely from graph
structure — so functional modules self-organize into visible clusters.

================================================================================
WHAT IS HuRI?
================================================================================

HuRI is the first proteome-scale, systematically assayed map of direct human
protein-protein interactions. It was generated by all-by-all yeast two-hybrid
(Y2H) screening of ~17k human ORFs against themselves. Unlike aggregated
databases such as STRING or BioGRID — which blend experimental evidence with
computational predictions, co-expression, and text-mining — every edge in
HuRI is a physically tested, directly observed binary interaction. The full
network is remarkably clean for a demo: one source, one experimental pipeline,
one interpretation per edge.

DATASET AT A GLANCE
-------------------
- ~8,275 proteins (Ensembl gene IDs mapped to HGNC symbols)
- ~52,569 binary, undirected Y2H interactions (after canonicalization)
- No native spatial coordinates — the layout is computed from the graph
  itself using spectral embedding + UMAP

LAYOUT
------
Nodes are positioned by a 2-step graph-geometry recipe:
    1. Spectral embedding: top-k smallest-eigenvalue eigenvectors of the
       normalized Laplacian. Each node becomes a point in a k-dim space
       where the graph's modular structure is preserved.
    2. UMAP reduction of that k-dim embedding to 3D.

The result is a coordinate system in which densely-interconnected
communities appear as spatial clusters.

COLOR / STRUCTURE
-----------------
Two runtime-switchable color views, chosen because they emphasise different
things about the interactome:

    - "Community" — Louvain communities from the network topology itself.
      These correspond loosely to biochemical modules (ribosome, nucleosome
      remodeling, proteasome, spliceosome, …). Colors are categorical.
    - "Chromosome" — HGNC-annotated chromosomal location. Useful for
      spotting clusters whose physical interaction module happens to be
      encoded on the same chromosome.

Edges are colored by their endpoints' relationship:
    - Intra-community edges inherit the community color (saturated).
    - Cross-community "bridge" edges are dim gray.

This makes modularity pop at a glance and tells the eye which edges are
worth hovering.

HOVER INFO
----------
- Node: gene symbol, chromosome, degree, community id
- Edge: GENE_A ⇄ GENE_B, intra- or cross-community label, and — where
        applicable — the shared CORUM complex the pair participates in.
        (CORUM is optional: if the download fails, edges still show their
         pair + community relation.)

DATA SOURCES
------------
- HuRI network:
    https://interactome-atlas.org/data/HuRI.tsv
    Luck et al., "A reference map of the human binary protein interactome",
    Nature 2020, https://doi.org/10.1038/s41586-020-2188-x
- HGNC (Ensembl → Symbol + chromosome mapping):
    https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt
- CORUM (shared-complex annotations, optional):
    https://mips.helmholtz-muenchen.de/corum/

The first run downloads ~35 MB total and computes the layout (~1 min).
Subsequent runs reuse the cache at ``~/.cache/luxar/huri/`` — including
the cached 3D coordinates.

Usage:
    python -m luxar.demos.demo_huri_interactome
    python -m luxar.demos.demo_huri_interactome --no-serve
    python -m luxar.demos.demo_huri_interactome --max-edges 30000
    python -m luxar.demos.demo_huri_interactome --recompute-layout
"""

from __future__ import annotations

DEMO_META = {
    "key": "huri_interactome",
    "title": "HuRI Interactome",
    "description": "The HuRI human protein interactome: ~8k proteins as Points, ~50k interactions as Lines.",
    "category": "networks",
    "geometry": "points+lines",
    "requirements": {
        "download_mb": 35,
        "compute": "medium",
        "gpu": "none",
        "local_data": None,
    },
    "caches": ["huri"],
    "outputs": ["huri_interactome"],
}

import hashlib
import sys
import tempfile
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
import requests
from arbol import aprint, asection

from luxar import Dimension, Dimensions, LuxarZarrCompiler
from luxar.demos import launch_viewer
from luxar.utils._umap_utils import build_legend_html, get_categorical_color
from luxar.utils.paths import get_demos_output_dir

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

CACHE_DIR = Path.home() / ".cache" / "luxar" / "huri"

HURI_URL = "https://interactome-atlas.org/data/HuRI.tsv"
HURI_FILENAME = "HuRI.tsv"

HGNC_URL = (
    "https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/"
    "hgnc_complete_set.txt"
)
HGNC_FILENAME = "hgnc_complete_set.txt"

# CORUM URLs are less stable across releases; we try candidates in order
# and fail gracefully (the demo still works without CORUM, the edge
# hover just omits the "shared complex" line).
CORUM_URLS: tuple[str, ...] = (
    "https://mips.helmholtz-muenchen.de/corum/download/releases/current/allComplexes.txt.zip",
    "https://mips.helmholtz-muenchen.de/corum/download/releases/2022.08/allComplexes.txt.zip",
)
CORUM_FILENAME = "allComplexes.txt"

LAYOUT_CACHE_FILENAME = "layout_3d.npz"

# Spectral + UMAP parameters
N_SPECTRAL_DIMS = 30
UMAP_N_NEIGHBORS = 15
UMAP_MIN_DIST = 0.3

# Visual caps
DEFAULT_MAX_EDGES = 60_000

# Download safety ceilings for the CORUM fallback. These third-party CORUM
# URLs shift across releases and are NOT controlled Luxar assets, so we bound
# both the compressed archive we stream to disk and the extracted (uncompressed)
# member — the latter guards against a decompression bomb. CORUM's real zip is
# only a few MB, so these are generous but hard caps, not tight limits. The
# archive cap is also what bounds the eager ZipFile central-directory parse: a
# zip entry costs at least ~76 bytes on disk (central + local header), so 64 MiB
# admits at most ~0.8M entries, i.e. a few hundred MB of transient ZipInfo
# objects in the pathological case — well under this demo's own working set, and
# a tighter bound than an entry-count preflight would add on top.
_CORUM_MAX_ARCHIVE_BYTES = 64 * 1024 * 1024  # 64 MiB compressed archive cap
_CORUM_MAX_MEMBER_BYTES = 512 * 1024 * 1024  # 512 MiB extracted member cap

CROSS_COMMUNITY_COLOR: tuple[float, float, float] = (0.30, 0.30, 0.32)


# -----------------------------------------------------------------------------
# Download / cache
# -----------------------------------------------------------------------------


def _download(url: str, dest: Path, description: str) -> None:
    """Stream a URL to ``dest``, with progress. No-op if file exists."""
    if dest.exists() and dest.stat().st_size > 0:
        size_mb = dest.stat().st_size / (1024 * 1024)
        aprint(f"  Using cached {dest.name} ({size_mb:.1f} MB)")
        return

    dest.parent.mkdir(parents=True, exist_ok=True)
    aprint(f"  Downloading {description}")
    aprint(f"    URL: {url}")

    tmp = dest.with_suffix(dest.suffix + ".part")
    with requests.get(url, stream=True, timeout=120) as r:
        r.raise_for_status()
        total = int(r.headers.get("content-length", 0))
        written = 0
        last_pct = 0.0
        with open(tmp, "wb") as f:
            for chunk in r.iter_content(chunk_size=1 << 20):
                if not chunk:
                    continue
                f.write(chunk)
                written += len(chunk)
                if total > 0:
                    pct = 100.0 * written / total
                    if pct - last_pct >= 20.0:
                        aprint(
                            f"    {written / (1024 * 1024):,.0f} / "
                            f"{total / (1024 * 1024):,.0f} MB  ({pct:.0f}%)"
                        )
                        last_pct = pct
    tmp.rename(dest)
    size_mb = dest.stat().st_size / (1024 * 1024)
    aprint(f"  ✓ Saved {dest.name} ({size_mb:.1f} MB)")


def _download_corum_zip_member(
    urls: tuple[str, ...], member_suffix: str, dest: Path, description: str
) -> bool:
    """Try each URL until one works; extract the matching member to ``dest``.

    Returns True on success, False if every URL failed or the member was
    missing. Designed for CORUM, whose URLs have shifted over time.
    """
    if dest.exists() and dest.stat().st_size > 0:
        size_mb = dest.stat().st_size / (1024 * 1024)
        aprint(f"  Using cached {dest.name} ({size_mb:.1f} MB)")
        return True

    dest.parent.mkdir(parents=True, exist_ok=True)
    archive_tmp = dest.with_name(dest.name + ".zip.part")
    part = dest.with_name(dest.name + ".part")
    for url in urls:
        try:
            aprint(f"  Trying {description}")
            aprint(f"    URL: {url}")
            # Stream the (untrusted) archive to disk under a hard size cap so we
            # never buffer the whole compressed body in RAM. Force identity
            # encoding so Content-Length matches the decoded byte stream (house
            # convention — see utils/download._force_identity_encoding).
            with requests.get(
                url,
                stream=True,
                timeout=60,
                headers={"Accept-Encoding": "identity"},
            ) as r:
                r.raise_for_status()
                # A malformed/duplicated Content-Length ("abc", "123, 123")
                # would raise on parse; treat any parse failure as unknown size
                # so the streaming running-total guard still bounds the body.
                try:
                    declared = int(r.headers.get("content-length", 0) or 0)
                except (TypeError, ValueError):
                    declared = 0
                if declared > _CORUM_MAX_ARCHIVE_BYTES:
                    raise ValueError(
                        f"archive too large: Content-Length {declared} bytes "
                        f"exceeds cap {_CORUM_MAX_ARCHIVE_BYTES}"
                    )
                written = 0
                with open(archive_tmp, "wb") as f:
                    for chunk in r.iter_content(chunk_size=1 << 20):
                        if not chunk:
                            continue
                        written += len(chunk)
                        if written > _CORUM_MAX_ARCHIVE_BYTES:
                            raise ValueError(
                                f"archive too large: exceeded cap "
                                f"{_CORUM_MAX_ARCHIVE_BYTES} bytes while streaming"
                            )
                        f.write(chunk)

            # Open the zip from the on-disk temp file (disk-backed, not in RAM).
            with zipfile.ZipFile(archive_tmp) as zf:
                names = zf.namelist()
                target = next((n for n in names if n.endswith(member_suffix)), None)
                if target is None:
                    shown = names[:20]
                    aprint(
                        f"    ⚠ {member_suffix} not in zip "
                        f"({len(names)} entries; first {len(shown)}: {shown})"
                    )
                    continue
                # CPython's ZipExtFile clamps decompressed output to the declared
                # file_size (and fails CRC), so this up-front declared-size check
                # is the effective decompression-bomb guard; the running-total
                # raise below is an unreachable defensive backstop.
                declared_member = zf.getinfo(target).file_size
                if declared_member > _CORUM_MAX_MEMBER_BYTES:
                    raise ValueError(
                        f"member too large: declared {declared_member} bytes "
                        f"exceeds cap {_CORUM_MAX_MEMBER_BYTES}"
                    )
                extracted = 0
                with zf.open(target) as src, open(part, "wb") as dst:
                    while True:
                        buf = src.read(1 << 20)
                        if not buf:
                            break
                        extracted += len(buf)
                        if extracted > _CORUM_MAX_MEMBER_BYTES:
                            raise ValueError(
                                f"member too large: exceeded cap "
                                f"{_CORUM_MAX_MEMBER_BYTES} bytes while extracting"
                            )
                        dst.write(buf)
            if extracted == 0:
                raise ValueError(f"member {target} is empty (0 bytes)")
            part.replace(dest)
            size_mb = dest.stat().st_size / (1024 * 1024)
            aprint(f"  ✓ Saved {dest.name} ({size_mb:.1f} MB)")
            return True
        except Exception as exc:  # noqa: BLE001
            aprint(f"    ⚠ Failed: {exc}")
            continue
        finally:
            archive_tmp.unlink(missing_ok=True)
            part.unlink(missing_ok=True)
    return False


def ensure_data(cache_dir: Path) -> tuple[Path, Path, Path | None]:
    """Fetch HuRI + HGNC (required) and CORUM (optional). Returns paths."""
    huri_path = cache_dir / HURI_FILENAME
    hgnc_path = cache_dir / HGNC_FILENAME
    corum_path = cache_dir / CORUM_FILENAME

    with asection("Fetching data"):
        _download(HURI_URL, huri_path, "HuRI network (~2 MB)")
        _download(HGNC_URL, hgnc_path, "HGNC complete set (~30 MB)")
        ok = _download_corum_zip_member(
            CORUM_URLS,
            CORUM_FILENAME,
            corum_path,
            "CORUM complexes (optional, enables 'shared complex' hovers)",
        )
        if not ok:
            aprint(
                "  CORUM unavailable — the demo will run without "
                "shared-complex hover annotations."
            )
    return huri_path, hgnc_path, corum_path if ok else None


# -----------------------------------------------------------------------------
# Data loading + HGNC mapping
# -----------------------------------------------------------------------------


def load_hgnc(tsv_path: Path) -> pd.DataFrame:
    """Return a frame indexed by Ensembl gene id with (symbol, chromosome)."""
    wanted = {"symbol", "ensembl_gene_id", "location", "status"}
    with asection("Loading HGNC (Ensembl → symbol)"):
        df = pd.read_csv(
            tsv_path,
            sep="\t",
            usecols=lambda c: c in wanted,
            dtype=str,
            low_memory=False,
        )
        if "status" in df.columns:
            df = df[df["status"] == "Approved"]
        df = df.dropna(subset=["ensembl_gene_id", "symbol"])
        # location like "17q21.31" or "Xp22.2" → chromosome prefix
        df["chromosome"] = (
            df.get("location", pd.Series([""] * len(df)))
            .fillna("?")
            .astype(str)
            .str.extract(r"^([0-9XYMT]+)", expand=False)
            .fillna("?")
        )
        df = df.set_index("ensembl_gene_id")[["symbol", "chromosome"]]
        df = df[~df.index.duplicated(keep="first")]
        aprint(f"  {len(df):,} Ensembl→symbol mappings")
    return df


def load_huri_edges(tsv_path: Path, hgnc: pd.DataFrame) -> pd.DataFrame:
    """Return the undirected, deduplicated (sym_a, sym_b) edge frame."""
    with asection("Loading HuRI interactions"):
        df = pd.read_csv(tsv_path, sep="\t", header=None, dtype=str, low_memory=False)
        if df.shape[1] < 2:
            raise RuntimeError(f"Unexpected HuRI format (got {df.shape[1]} columns)")
        df = df.iloc[:, :2].copy()
        df.columns = ["ensg_a", "ensg_b"]
        # Filter to ENSG-looking rows (handles presence or absence of header)
        df = df[
            df["ensg_a"].str.startswith("ENSG", na=False)
            & df["ensg_b"].str.startswith("ENSG", na=False)
        ]
        df = df[df["ensg_a"] != df["ensg_b"]]
        aprint(f"  {len(df):,} ENSG-level pairs")

        symbol_map = hgnc["symbol"].to_dict()
        sym_a = df["ensg_a"].map(symbol_map)
        sym_b = df["ensg_b"].map(symbol_map)
        keep = sym_a.notna() & sym_b.notna()
        df = pd.DataFrame(
            {"sym_a": sym_a[keep].to_numpy(), "sym_b": sym_b[keep].to_numpy()}
        )
        aprint(f"  {len(df):,} pairs with both endpoints mapped to HGNC")

        # Canonicalize so (A, B) == (B, A) then drop duplicates
        a = df["sym_a"].to_numpy()
        b = df["sym_b"].to_numpy()
        lo = np.where(a < b, a, b)
        hi = np.where(a < b, b, a)
        df = pd.DataFrame({"sym_a": lo, "sym_b": hi}).drop_duplicates()
        aprint(f"  {len(df):,} unique undirected pairs")
    return df.reset_index(drop=True)


def filter_to_lcc(
    edges: pd.DataFrame, hgnc: pd.DataFrame
) -> tuple[list[str], pd.DataFrame, pd.DataFrame]:
    """Restrict to the largest connected component and attach chromosome info."""
    try:
        import networkx as nx  # noqa: F401
    except ImportError:
        aprint("❌ Missing dependency: networkx (>=3.0 for louvain_communities)")
        aprint("   Install with: pip install 'networkx>=3.0'")
        raise

    import networkx as nx

    with asection("Filtering to largest connected component"):
        g = nx.Graph()
        g.add_edges_from(
            zip(edges["sym_a"].tolist(), edges["sym_b"].tolist(), strict=True)
        )
        components = sorted(nx.connected_components(g), key=len, reverse=True)
        lcc = components[0]
        aprint(
            f"  {len(components):,} components; LCC has "
            f"{len(lcc):,} nodes (dropped {g.number_of_nodes() - len(lcc):,})"
        )

        lcc_set = set(lcc)
        mask = edges["sym_a"].isin(lcc_set) & edges["sym_b"].isin(lcc_set)
        edges = edges[mask].reset_index(drop=True)
        aprint(f"  {len(edges):,} edges within the LCC")

        nodes = sorted(lcc_set)  # deterministic order → reproducible layout
        sym_to_chrom = hgnc.groupby("symbol")["chromosome"].first().to_dict()
        node_df = pd.DataFrame(
            {
                "symbol": nodes,
                "chromosome": [sym_to_chrom.get(s, "?") for s in nodes],
            }
        )
    return nodes, node_df, edges


# -----------------------------------------------------------------------------
# Layout: spectral embedding → UMAP → 3D
# -----------------------------------------------------------------------------


def _build_adjacency(nodes: list[str], edges: pd.DataFrame):
    """Return a symmetric CSR adjacency matrix, one entry per undirected edge."""
    from scipy.sparse import csr_matrix

    idx = {s: i for i, s in enumerate(nodes)}
    rows = np.fromiter((idx[s] for s in edges["sym_a"]), dtype=np.int32)
    cols = np.fromiter((idx[s] for s in edges["sym_b"]), dtype=np.int32)
    data = np.ones(len(edges), dtype=np.float32)
    n = len(nodes)
    mat = csr_matrix(
        (
            np.concatenate([data, data]),
            (np.concatenate([rows, cols]), np.concatenate([cols, rows])),
        ),
        shape=(n, n),
    )
    mat.sum_duplicates()
    mat.data = np.minimum(mat.data, 1.0)
    return mat


def _nodes_hash(nodes: list[str]) -> str:
    """Deterministic hash of the node list for layout cache invalidation."""
    return hashlib.sha256("\n".join(nodes).encode("utf-8")).hexdigest()[:16]


def compute_layout(
    nodes: list[str], edges: pd.DataFrame, cache_path: Path, recompute: bool
) -> np.ndarray:
    """Spectral embedding + UMAP → 3D coordinates, cached to npz."""
    node_hash = _nodes_hash(nodes)

    if cache_path.exists() and not recompute:
        with asection("Loading cached 3D layout"):
            data = np.load(cache_path, allow_pickle=False)
            cached_hash = str(data["node_hash"])
            if cached_hash == node_hash:
                coords = data["coords"].astype(np.float32)
                aprint(f"  Loaded {len(coords):,} coords from cache")
                return coords
            aprint("  Node set changed — recomputing layout")

    from scipy.sparse import eye as speye
    from scipy.sparse.csgraph import laplacian
    from scipy.sparse.linalg import eigsh

    with asection("Computing spectral + UMAP layout"):
        adj = _build_adjacency(nodes, edges)
        aprint(f"  Adjacency: {adj.shape[0]} × {adj.shape[0]}, nnz={adj.nnz:,}")

        lap = laplacian(adj, normed=True).astype(np.float64)
        # Solve for top-k LARGEST eigenvalues of (I - L); these correspond
        # to the SMALLEST eigenvalues of L. Avoids shift-invert around 0,
        # which is numerically unstable when L has a zero eigenvalue.
        shifted = speye(lap.shape[0], format="csr") - lap
        k = min(N_SPECTRAL_DIMS + 1, adj.shape[0] - 2)
        aprint(f"  Computing {k} eigenvectors (normalized Laplacian)")
        eigvals_shift, eigvecs = eigsh(shifted, k=k, which="LA")

        # Sort: L-eigenvalues smallest first (i.e. shifted largest first)
        order = np.argsort(eigvals_shift)[::-1]
        eigvecs = eigvecs[:, order]
        # Drop the trivial (constant) eigenvector
        features = eigvecs[:, 1:].astype(np.float32)
        # Row-normalize — standard for normalized spectral clustering
        norms = np.linalg.norm(features, axis=1, keepdims=True)
        features = features / np.maximum(norms, 1e-10)
        aprint(f"  Spectral features: {features.shape}")

        try:
            from umap import UMAP
        except ImportError:
            aprint("❌ Missing dependency: umap-learn")
            aprint("   Install with: pip install umap-learn")
            raise

        reducer = UMAP(
            n_components=3,
            n_neighbors=UMAP_N_NEIGHBORS,
            min_dist=UMAP_MIN_DIST,
            metric="euclidean",
            n_jobs=-1,
            verbose=False,
        )
        coords = reducer.fit_transform(features).astype(np.float32)
        coords -= coords.mean(axis=0)
        # Rescale so 95th-percentile radius ~= 10 units (comfortable framing)
        radius_95 = float(np.percentile(np.linalg.norm(coords, axis=1), 95))
        if radius_95 > 0:
            coords *= 10.0 / radius_95
        aprint(
            f"  Coords (µu): x range {np.ptp(coords[:, 0]):.1f}, "
            f"y {np.ptp(coords[:, 1]):.1f}, z {np.ptp(coords[:, 2]):.1f}"
        )

        cache_path.parent.mkdir(parents=True, exist_ok=True)
        np.savez(cache_path, coords=coords, node_hash=np.array(node_hash))
        aprint(f"  Cached to {cache_path.name}")
    return coords


# -----------------------------------------------------------------------------
# Communities + CORUM
# -----------------------------------------------------------------------------


def compute_communities(nodes: list[str], edges: pd.DataFrame) -> np.ndarray:
    """Louvain community assignment per node. Communities sorted by size desc."""
    import networkx as nx

    with asection("Detecting communities (Louvain)"):
        g = nx.Graph()
        g.add_nodes_from(nodes)
        g.add_edges_from(
            zip(edges["sym_a"].tolist(), edges["sym_b"].tolist(), strict=True)
        )
        partitions = nx.community.louvain_communities(g, seed=42)
        partitions = sorted(partitions, key=len, reverse=True)
        aprint(f"  {len(partitions)} communities detected")
        for i, p in enumerate(partitions[:5]):
            aprint(f"    #{i}: {len(p):,} nodes")
        if len(partitions) > 5:
            aprint(f"    ... + {len(partitions) - 5} smaller")

        idx = {s: i for i, s in enumerate(nodes)}
        comms = np.full(len(nodes), -1, dtype=np.int32)
        for comm_id, members in enumerate(partitions):
            for symbol in members:
                comms[idx[symbol]] = comm_id
    return comms


def load_corum_lookup(
    corum_path: Path | None,
) -> dict[frozenset, list[str]]:
    """Build {frozenset({symA, symB}) → [complex_name, ...]} for human pairs."""
    if corum_path is None or not corum_path.exists():
        return {}

    with asection("Loading CORUM complex memberships"):
        df = pd.read_csv(corum_path, sep="\t", low_memory=False, dtype=str)
        aprint(f"  {len(df):,} rows, {df.shape[1]} columns")

        # Column names vary mildly across CORUM releases
        def _find(cols_lower_contains: list[str]) -> str | None:
            for c in df.columns:
                cl = c.lower()
                if all(tok in cl for tok in cols_lower_contains):
                    return c
            return None

        name_col = _find(["complexname"])
        subunit_col = _find(["subunits", "gene name"])
        organism_col = _find(["organism"])
        if name_col is None or subunit_col is None:
            aprint(
                f"  ⚠ Could not find CORUM name/subunit columns "
                f"(have: {list(df.columns)[:8]}...); skipping"
            )
            return {}

        if organism_col is not None:
            organism = df[organism_col].fillna("").str.lower()
            df = df[organism.isin({"human", "homo sapiens", "mammalia, human"})]
            aprint(f"  {len(df):,} human complexes")

        pair_to_complexes: dict[frozenset, list[str]] = {}
        for row in df[[name_col, subunit_col]].itertuples(index=False):
            name, subunits = row
            if not isinstance(subunits, str) or not subunits.strip():
                continue
            for delim in (";", ",", "|"):
                if delim in subunits:
                    subs = [s.strip() for s in subunits.split(delim) if s.strip()]
                    break
            else:
                subs = [subunits.strip()]
            if len(subs) < 2:
                continue
            for i in range(len(subs)):
                for j in range(i + 1, len(subs)):
                    key = frozenset({subs[i], subs[j]})
                    pair_to_complexes.setdefault(key, []).append(str(name))

        aprint(f"  {len(pair_to_complexes):,} protein pairs in ≥1 CORUM complex")
    return pair_to_complexes


# -----------------------------------------------------------------------------
# Geometry builders
# -----------------------------------------------------------------------------


def _community_palette(n_comms: int) -> np.ndarray:
    """(n_comms, 3) float32 in [0,1]."""
    return (
        np.array(
            [get_categorical_color(i, n_comms) for i in range(n_comms)],
            dtype=np.float32,
        )
        / 255.0
    )


def build_node_points(
    nodes: list[str],
    node_df: pd.DataFrame,
    coords: np.ndarray,
    communities: np.ndarray,
    degrees: np.ndarray,
) -> tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    list[str],
    list[str],
    np.ndarray,
    np.ndarray,
    np.ndarray,
]:
    """Assemble Points attributes duplicated across both color views.

    Returns:
        positions (2N, 4), colors (2N, 3), radii (2N,), labels (2N,),
        chrom_categories, chrom_codes (N,), community_palette (K, 3),
        chrom_palette (C, 3)
    """
    n = len(nodes)

    # Community colors
    n_comms = int(communities.max()) + 1
    comm_palette = _community_palette(n_comms)
    comm_colors = comm_palette[communities]

    # Chromosome colors (deterministic category order: numeric then X/Y/MT/?)
    def _chrom_sort_key(c: str) -> tuple[int, str]:
        if c == "?":
            return (99, "")
        if c.isdigit():
            return (int(c), "")
        return (50, c)  # X, Y, MT before "?"

    chroms = node_df["chromosome"].tolist()
    chrom_cats = sorted(set(chroms), key=_chrom_sort_key)
    chrom_idx = {c: i for i, c in enumerate(chrom_cats)}
    chrom_codes = np.array([chrom_idx[c] for c in chroms], dtype=np.int32)
    chrom_palette = (
        np.array(
            [get_categorical_color(i, len(chrom_cats)) for i in range(len(chrom_cats))],
            dtype=np.float32,
        )
        / 255.0
    )
    chrom_colors = chrom_palette[chrom_codes]

    # Radii scale with log(degree) so hubs are visible
    log_deg = np.log1p(degrees.astype(np.float32))
    log_deg /= max(float(log_deg.max()), 1.0)
    radii_per_node = (0.06 + 0.18 * log_deg).astype(np.float32)

    # Positions for two views stacked
    n_verts_per_view = n
    pos_view0 = np.empty((n_verts_per_view, 4), dtype=np.float32)
    pos_view0[:, 0] = 0.0
    pos_view0[:, 1:] = coords
    pos_view1 = pos_view0.copy()
    pos_view1[:, 0] = 1.0
    positions = np.vstack([pos_view0, pos_view1])

    colors = np.vstack([comm_colors, chrom_colors])
    radii = np.concatenate([radii_per_node, radii_per_node])

    # Hover labels (one per vertex, replicated per view)
    per_node_labels = [
        f"{sym}\n[chr{ch} · deg {int(d)} · community {int(c)}]"
        for sym, ch, d, c in zip(nodes, chroms, degrees, communities, strict=True)
    ]
    labels = per_node_labels * 2

    return (
        positions,
        colors,
        radii,
        labels,
        chrom_cats,
        chrom_codes,
        comm_palette,
        chrom_palette,
    )


def build_edge_lines(
    nodes: list[str],
    edges: pd.DataFrame,
    communities: np.ndarray,
    comm_palette: np.ndarray,
    coords: np.ndarray,
    corum_lookup: dict[frozenset, list[str]],
    max_edges: int,
) -> tuple[pd.DataFrame, np.ndarray, np.ndarray, np.ndarray, list[str]]:
    """Assemble Lines attributes, duplicated across both views.

    Intra-community edges get the community's color (saturated); cross-
    community edges get dim gray. Width is slightly heavier for intra-
    community edges so the modular structure reads clearly.

    Returns:
        final_edges, vertices (4E, 4), widths (4E,), colors (4E, 3),
        labels (4E,)
    """
    idx = {s: i for i, s in enumerate(nodes)}
    a_idx = np.fromiter((idx[s] for s in edges["sym_a"]), dtype=np.int32)
    b_idx = np.fromiter((idx[s] for s in edges["sym_b"]), dtype=np.int32)
    same = communities[a_idx] == communities[b_idx]

    # Subsample if too many edges; keep intra-community preferentially
    if len(edges) > max_edges:
        with asection("Subsampling edges (cap preserves intra-community)"):
            n_same = int(same.sum())
            n_cross = int(len(edges) - n_same)
            rng = np.random.default_rng(42)

            if n_same > max_edges:
                same_positions = np.nonzero(same)[0]
                chosen_same = rng.choice(same_positions, size=max_edges, replace=False)
                keep = np.zeros(len(edges), dtype=bool)
                keep[chosen_same] = True
            else:
                target_cross = max_edges - n_same
                cross_positions = np.nonzero(~same)[0]
                chosen_cross = rng.choice(
                    cross_positions,
                    size=min(target_cross, n_cross),
                    replace=False,
                )
                keep = same.copy()
                keep[chosen_cross] = True

            edges = edges.loc[keep].reset_index(drop=True)
            a_idx = np.fromiter((idx[s] for s in edges["sym_a"]), dtype=np.int32)
            b_idx = np.fromiter((idx[s] for s in edges["sym_b"]), dtype=np.int32)
            same = communities[a_idx] == communities[b_idx]
            aprint(
                f"  Kept {len(edges):,} edges: "
                f"{int(same.sum()):,} intra-community + "
                f"{int((~same).sum()):,} cross-community"
            )

    n_edges = len(edges)
    xs, ys, zs = coords[:, 0], coords[:, 1], coords[:, 2]

    # Vertices per view: (n_edges × 2, 3) flat
    verts_xyz = np.empty((n_edges, 2, 3), dtype=np.float32)
    verts_xyz[:, 0, 0] = xs[a_idx]
    verts_xyz[:, 0, 1] = ys[a_idx]
    verts_xyz[:, 0, 2] = zs[a_idx]
    verts_xyz[:, 1, 0] = xs[b_idx]
    verts_xyz[:, 1, 1] = ys[b_idx]
    verts_xyz[:, 1, 2] = zs[b_idx]
    flat_xyz = verts_xyz.reshape(n_edges * 2, 3)

    view0_col = np.zeros((n_edges * 2, 1), dtype=np.float32)
    view1_col = np.ones((n_edges * 2, 1), dtype=np.float32)
    verts_v0 = np.hstack([view0_col, flat_xyz])
    verts_v1 = np.hstack([view1_col, flat_xyz])
    vertices = np.vstack([verts_v0, verts_v1])

    # Widths (same at both endpoints — interactions are symmetric)
    width_per_edge = np.where(same, 0.015, 0.009).astype(np.float32)
    width_per_vertex_1view = np.repeat(width_per_edge, 2)
    widths = np.concatenate([width_per_vertex_1view, width_per_vertex_1view])

    # Colors
    same_rgb = comm_palette[communities[a_idx]]
    cross_rgb = np.tile(np.array(CROSS_COMMUNITY_COLOR, dtype=np.float32), (n_edges, 1))
    rgb_per_edge = np.where(same[:, None], same_rgb, cross_rgb).astype(np.float32)
    rgb_per_vertex_1view = np.repeat(rgb_per_edge, 2, axis=0)
    colors = np.vstack([rgb_per_vertex_1view, rgb_per_vertex_1view])

    # Labels — with optional CORUM shared-complex line
    labels_per_edge: list[str] = []
    syms_a = edges["sym_a"].tolist()
    syms_b = edges["sym_b"].tolist()
    for i in range(n_edges):
        sa, sb = syms_a[i], syms_b[i]
        pieces = [f"{sa} ⇄ {sb}"]
        if same[i]:
            pieces.append(f"[intra-community #{int(communities[a_idx[i]])}]")
        else:
            pieces.append("[cross-community bridge]")
        shared = corum_lookup.get(frozenset({sa, sb}))
        if shared:
            names = list(dict.fromkeys(shared))  # dedupe, preserve order
            shown = names[:2]
            suffix = f" (+{len(names) - 2} more)" if len(names) > 2 else ""
            pieces.append("Shared complex: " + "; ".join(shown) + suffix)
        labels_per_edge.append("\n".join(pieces))

    labels_per_vertex_1view: list[str] = []
    for lab in labels_per_edge:
        labels_per_vertex_1view.extend([lab, lab])
    labels = labels_per_vertex_1view * 2  # both views share the same labels

    return edges, vertices, widths, colors, labels


# -----------------------------------------------------------------------------
# Legends
# -----------------------------------------------------------------------------


def _build_community_legend(communities: np.ndarray, top_n: int = 20) -> str:
    """Top-N communities by size, sorted descending."""
    unique, counts = np.unique(communities, return_counts=True)
    order = np.argsort(-counts)
    unique = unique[order]
    counts = counts[order]
    n_comms = len(unique)
    lines = [
        '<div style="font-size:1.3vh;line-height:1.5;'
        "background:rgba(0,0,0,0.55);padding:0.6vh 0.8vh;"
        'border-radius:4px;max-height:82vh;overflow:hidden">'
        '<div style="color:#ffcc44;font-weight:bold;margin-bottom:0.4vh">'
        f"Community ({n_comms})</div>"
    ]
    for comm_id, count in zip(unique[:top_n], counts[:top_n], strict=True):
        r, g, b = get_categorical_color(int(comm_id), n_comms)
        lines.append(
            f'<div style="white-space:nowrap">'
            f'<span style="color:rgb({r},{g},{b})">█</span> '
            f"#{int(comm_id)} ({int(count):,})</div>"
        )
    if n_comms > top_n:
        lines.append(f'<div style="color:#888">... +{n_comms - top_n} more</div>')
    lines.append("</div>")
    return "".join(lines)


# -----------------------------------------------------------------------------
# Scene
# -----------------------------------------------------------------------------


def build_scene(
    output_path: Path,
    nodes: list[str],
    node_df: pd.DataFrame,
    edges: pd.DataFrame,
    coords: np.ndarray,
    communities: np.ndarray,
    degrees: np.ndarray,
    corum_lookup: dict[frozenset, list[str]],
    max_edges: int,
) -> tuple[int, int, int]:
    """Write the Luxar zarr scene. Returns (n_nodes, n_edges_kept, n_communities)."""
    (
        node_positions,
        node_colors,
        node_radii,
        node_labels,
        chrom_cats,
        chrom_codes,
        comm_palette,
        _chrom_palette,
    ) = build_node_points(nodes, node_df, coords, communities, degrees)

    edges_kept, verts, widths, edge_colors, edge_labels = build_edge_lines(
        nodes,
        edges,
        communities,
        comm_palette,
        coords,
        corum_lookup,
        max_edges=max_edges,
    )

    n_nodes = len(nodes)
    n_edges_kept = len(edges_kept)
    n_comms = int(communities.max()) + 1

    corum_hits_kept = (
        sum(
            1
            for sa, sb in zip(edges_kept["sym_a"], edges_kept["sym_b"], strict=True)
            if frozenset({sa, sb}) in corum_lookup
        )
        if corum_lookup
        else 0
    )

    with asection("Building Luxar scene"):
        dims = Dimensions(
            [
                Dimension(
                    "view",
                    unit="",
                    categories=["Community", "Chromosome"],
                    display=False,
                    description=("Color coding (press '1' then '[' / ']' to switch)"),
                ),
                Dimension("x", unit="UMAP", display=True),
                Dimension("y", unit="UMAP", display=True),
                Dimension("z", unit="UMAP", display=True),
            ]
        )

        with LuxarZarrCompiler(output_path) as compiler:
            scene = compiler.create_scene(dimensions=dims)

            scene.add_points(
                "Proteins",
                positions=node_positions,
                colors=node_colors,
                radii=node_radii,
                sharpness=np.full(len(node_positions), 0.55, dtype=np.float32),
                opacity=0.95,
                intensity=0.2,
                labels=node_labels,
                layer=True,
            )

            if len(verts) > 0:
                scene.add_lines(
                    "Interactions",
                    vertices=verts,
                    widths=widths,
                    colors=edge_colors,
                    sharpness=np.full(len(verts), 0.85, dtype=np.float32),
                    line_type="segments",
                    blending_mode="luminous",
                    opacity=0.40,
                    intensity=0.5,
                    labels=edge_labels,
                    layer=True,
                )

            # Title
            scene.add_text(
                "HuRI — Human Reference Interactome",
                position=(0.02, 0.02),
                font_size=0.05,
                anchor="top-left",
                color="rgba(255,255,255,0.65)",
                blend_mode="difference",
            )

            # Hover overlay (center-left avoids clipping the right-side legend)
            scene.add_text(
                "{hover_label}",
                position=(0.02, 0.5),
                anchor="center-left",
                font_size=0.022,
                color="white",
                background="rgba(0,0,0,0.72)",
                padding=0.01,
                text_align="left",
                opacity=1.0,
                transition="fade",
                transition_duration=0.15,
                hover=True,
            )

            # Per-view captions + legends
            community_legend = _build_community_legend(communities)
            chrom_legend = build_legend_html("chromosome", chrom_cats, chrom_codes)

            for view_id, caption, legend_html in [
                (0, "Colored by: Community (Louvain)", community_legend),
                (1, "Colored by: Chromosome (HGNC)", chrom_legend),
            ]:
                scene.add_text(
                    caption,
                    position=(0.02, 0.97),
                    font_size=0.015,
                    anchor="bottom-left",
                    color="#ffcc44",
                    visible_range={"view": view_id},
                    transition="fade",
                    transition_duration=0.2,
                )
                if legend_html:
                    scene.add_html(
                        legend_html,
                        position=(0.98, 0.5),
                        anchor="center-right",
                        opacity=0.92,
                        visible_range={"view": view_id},
                        transition="fade",
                        transition_duration=0.2,
                    )

            # Footer
            footer = [
                f"{n_nodes:,} proteins",
                f"{n_edges_kept:,} interactions",
                f"{n_comms} communities",
            ]
            if corum_hits_kept:
                footer.append(f"{corum_hits_kept:,} CORUM-backed edges")
            footer.append("Luck et al., Nature 2020")
            scene.add_text(
                " · ".join(footer),
                position=(0.98, 0.97),
                font_size=0.012,
                anchor="bottom-right",
                color="rgba(200,200,200,0.5)",
            )

        aprint(
            f"  ✓ Scene: {n_nodes:,} nodes, {n_edges_kept:,} edges, "
            f"{n_comms} communities"
        )

    return n_nodes, n_edges_kept, n_comms


# -----------------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------------


def _int_arg(argv: list[str], flag: str, default: int) -> int:
    for i, arg in enumerate(argv):
        if arg == flag and i + 1 < len(argv):
            return int(argv[i + 1])
        if arg.startswith(flag + "="):
            return int(arg.split("=", 1)[1])
    return default


def _path_arg(argv: list[str], flag: str) -> Path | None:
    for i, arg in enumerate(argv):
        if arg == flag and i + 1 < len(argv):
            return Path(argv[i + 1]).expanduser()
        if arg.startswith(flag + "="):
            return Path(arg.split("=", 1)[1]).expanduser()
    return None


def _node_degrees(nodes: list[str], edges: pd.DataFrame) -> np.ndarray:
    """Degree per node, in the same order as ``nodes``."""
    counts = pd.concat([edges["sym_a"], edges["sym_b"]]).value_counts()
    return counts.reindex(nodes, fill_value=0).to_numpy(dtype=np.int32)


def main() -> None:
    argv = sys.argv[1:]
    max_edges = _int_arg(argv, "--max-edges", DEFAULT_MAX_EDGES)
    cache_dir = _path_arg(argv, "--cache-dir") or CACHE_DIR
    recompute = "--recompute-layout" in argv

    aprint("=" * 70)
    aprint("HuRI — Human Reference Interactome")
    aprint("=" * 70)
    aprint("~8k proteins · ~53k binary Y2H interactions · Luck et al. 2020")
    aprint(f"Edge cap: {max_edges:,}")
    aprint("")

    huri_path, hgnc_path, corum_path = ensure_data(cache_dir)
    hgnc = load_hgnc(hgnc_path)
    edges_raw = load_huri_edges(huri_path, hgnc)
    nodes, node_df, edges = filter_to_lcc(edges_raw, hgnc)
    coords = compute_layout(
        nodes,
        edges,
        cache_path=cache_dir / LAYOUT_CACHE_FILENAME,
        recompute=recompute,
    )
    communities = compute_communities(nodes, edges)
    degrees = _node_degrees(nodes, edges)
    corum_lookup = load_corum_lookup(corum_path)

    if "--no-serve" in argv:
        output_path = get_demos_output_dir() / "huri_interactome.luxar.zarr"
        build_scene(
            output_path,
            nodes,
            node_df,
            edges,
            coords,
            communities,
            degrees,
            corum_lookup,
            max_edges,
        )
        aprint(f"Dataset generated at {output_path}")
        return

    with tempfile.TemporaryDirectory(prefix="luxar_huri_") as tmpdir:
        output_path = Path(tmpdir) / "huri_interactome.luxar.zarr"
        n_nodes, n_edges, n_comms = build_scene(
            output_path,
            nodes,
            node_df,
            edges,
            coords,
            communities,
            degrees,
            corum_lookup,
            max_edges,
        )

        aprint("")
        aprint("=" * 70)
        aprint("NAVIGATION")
        aprint("=" * 70)
        aprint("  Press '1' then '[' / ']' to switch color view:")
        aprint("     0: Community  (Louvain — functional modules)")
        aprint("     1: Chromosome (HGNC location)")
        aprint("  Hover any node : symbol · chromosome · degree · community")
        aprint("  Hover any edge : pair · intra/cross · shared CORUM complex")
        aprint("")
        aprint(
            f"  Proteins: {n_nodes:,}   Interactions: {n_edges:,}   "
            f"Communities: {n_comms}"
        )
        aprint("")

        launch_viewer(output_path)

    aprint("Cleanup complete")


if __name__ == "__main__":
    main()
