/**
 * Unit tests for loadAndDecodeOptionalArray
 * (data/array-decoder/load-and-decode.ts).
 *
 * This helper opens a sibling zarr array, reads its attrs, decodes it via
 * a real `ArrayDecoder`, and returns the float buffer — or `null` when the
 * array is missing (the array is "optional").
 *
 * Testing strategy:
 *  - Success path: run against a REAL filesystem zarr fixture with a REAL
 *    ArrayDecoder. Only `log.success` is spied (to assert the success-log
 *    fires with the right element count). Nothing in the unit is mocked.
 *  - Missing path: spy on the zarr boundary (`zarr.open`) so it throws like a
 *    not-found, and assert the helper swallows it, returns null, and does NOT
 *    log success.
 *  - Error path: spy on `zarr.open` to return an array whose decode throws,
 *    and assert the helper swallows it the same way (returns null) — matching
 *    the real catch-all behavior of the source.
 *
 * Fixtures are generated by tests/fixtures/generate_test_data.py.
 */

import { describe, it, expect, vi, afterEach } from 'vitest';
import { loadAndDecodeOptionalArray } from '../../../../data/array-decoder/load-and-decode';
import { ArrayDecoder } from '../../../../data/array-decoder/decoder';
import { ArrayRefRegistry } from '../../../../data/array-decoder/ref-registry';
import * as zarr from '../../../../data/zarr';
import { log } from '../../../../utils/log';
import { FileSystemStore } from '@zarrita/storage';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FIXTURES_DIR = path.resolve(__dirname, '../../../../../tests/fixtures');

/** Open a real filesystem-backed zarr root location for a fixture dataset. */
async function openFixtureRoot(datasetName: string): Promise<zarr.Location<zarr.Readable>> {
  const rawStore = new FileSystemStore(path.join(FIXTURES_DIR, datasetName));
  const store = await zarr.openStore(rawStore);
  return zarr.root(store);
}

afterEach(() => {
  vi.restoreAllMocks();
});

describe('loadAndDecodeOptionalArray', () => {
  describe('success path (real fixture, real decoder)', () => {
    it('returns the decoded array and threads expectedElements through the decoder', async () => {
      // test_broadcasting.luxar.zarr "points/positions" is direct float32 (decodes in
      // Node without blosc): 1000 points x 3 dims = 3000 elements.
      const root = await openFixtureRoot('test_broadcasting.luxar.zarr');
      const pointsLoc = root.resolve('points');
      const decoder = new ArrayDecoder(new ArrayRefRegistry());

      const successSpy = vi.spyOn(log, 'success');

      const decoded = await loadAndDecodeOptionalArray(pointsLoc, 'positions', decoder, 1000);

      expect(decoded).not.toBeNull();
      expect(decoded).toBeInstanceOf(Float32Array);
      expect(decoded!.length).toBe(1000 * 3);

      // Success log must fire exactly once and report the decoded element count.
      expect(successSpy).toHaveBeenCalledTimes(1);
      const successMessage = successSpy.mock.calls[0][1];
      expect(successMessage).toContain('positions');
      expect(successMessage).toContain(String(1000 * 3));
    });

    it('passes attrs and expectedElements straight to decoder.decode', async () => {
      const root = await openFixtureRoot('test_broadcasting.luxar.zarr');
      const pointsLoc = root.resolve('points');
      const decoder = new ArrayDecoder(new ArrayRefRegistry());

      // Spy on the decode method without replacing decoder behaviour, so we can
      // assert the exact arguments the helper threads through.
      const decodeSpy = vi.spyOn(decoder, 'decode');

      const decoded = await loadAndDecodeOptionalArray(pointsLoc, 'positions', decoder, 1000);

      expect(decoded).not.toBeNull();
      expect(decodeSpy).toHaveBeenCalledTimes(1);

      const [arrayArg, attrsArg, expectedArg] = decodeSpy.mock.calls[0];
      // The decoder receives the opened zarr array (has shape/dtype),
      expect(arrayArg).toBeDefined();
      expect((arrayArg as { shape?: number[] }).shape).toBeDefined();
      // the array's attrs object (the encoding metadata),
      expect(attrsArg).toBeDefined();
      expect(attrsArg).toBe((arrayArg as { attrs: unknown }).attrs);
      // and the expectedElements value verbatim.
      expect(expectedArg).toBe(1000);
    });
  });

  describe('missing path (array not found)', () => {
    it('returns null and does NOT log success when zarr.open throws not-found', async () => {
      const root = await openFixtureRoot('test_broadcasting.luxar.zarr');
      const pointsLoc = root.resolve('points');
      const decoder = new ArrayDecoder(new ArrayRefRegistry());

      // Boundary mock: simulate a missing array — zarr.open rejects.
      const openSpy = vi
        .spyOn(zarr, 'open')
        .mockRejectedValue(new Error('Node not found: /points/does_not_exist'));
      const successSpy = vi.spyOn(log, 'success');
      const decodeSpy = vi.spyOn(decoder, 'decode');

      const result = await loadAndDecodeOptionalArray(pointsLoc, 'does_not_exist', decoder);

      expect(result).toBeNull();
      expect(openSpy).toHaveBeenCalledTimes(1);
      // Decoder must never run for a missing array.
      expect(decodeSpy).not.toHaveBeenCalled();
      // No spurious success log for an absent optional array.
      expect(successSpy).not.toHaveBeenCalled();
    });

    it('returns null for a non-existent array name against the real store', async () => {
      // End-to-end through the real store (no mock): a genuinely absent array
      // must yield null, not throw.
      const root = await openFixtureRoot('test_broadcasting.luxar.zarr');
      const pointsLoc = root.resolve('points');
      const decoder = new ArrayDecoder(new ArrayRefRegistry());

      const result = await loadAndDecodeOptionalArray(
        pointsLoc,
        'totally_absent_array',
        decoder,
        1000
      );

      expect(result).toBeNull();
    });
  });

  describe('error path (decoder throws)', () => {
    it('swallows a decoder error and returns null (matches source catch-all)', async () => {
      const root = await openFixtureRoot('test_broadcasting.luxar.zarr');
      const pointsLoc = root.resolve('points');
      const decoder = new ArrayDecoder(new ArrayRefRegistry());

      // Make decode reject; the helper's bare `catch {}` should absorb it.
      const decodeSpy = vi.spyOn(decoder, 'decode').mockRejectedValue(new Error('decode boom'));
      const successSpy = vi.spyOn(log, 'success');

      const result = await loadAndDecodeOptionalArray(pointsLoc, 'positions', decoder, 1000);

      // Real array opened fine, decode threw -> helper returns null, no success log.
      expect(decodeSpy).toHaveBeenCalledTimes(1);
      expect(result).toBeNull();
      expect(successSpy).not.toHaveBeenCalled();
    });
  });
});
