/**
 * Core type definitions for nD data visualization in Luxar.
 *
 * This module provides the fundamental data structures for managing
 * high-dimensional points data, including dimension metadata,
 * slicing state, and initialization utilities.
 */

import { log, Modules } from '../utils/log';

/**
 * Metadata describing the properties and behavior of a single dimension.
 *
 * Each dimension in an nD dataset can have rich metadata that controls
 * how it's displayed, navigated, and interpreted by the visualization system.
 *
 * This interface mirrors Python's luxar.core.Dimension class to ensure
 * full compatibility with datasets generated by the Python encoder.
 *
 * @interface DimensionMetadata
 */
export interface DimensionMetadata {
  /** Human-readable name for this dimension (e.g., "Time", "X", "Channel") */
  name: string;

  /** Physical unit of measurement (e.g., "μm", "s", "nm") */
  unit: string;

  /** Scale factor for converting from array indices to real-world units */
  scale: number;

  /** Optional min/max bounds for this dimension in real-world units */
  range?: [number, number];

  /** Whether this dimension should be displayed in the 3D scene by default */
  display?: boolean;

  /** Whether values in this dimension are discrete (integers) vs continuous */
  discrete?: boolean;

  /** Whether dimension wraps around (for angles, periodic states) */
  cyclic?: boolean;

  /** Step size for navigation in this dimension */
  step?: number;

  /** Whether points extend through this dimension (true for spatial dims) */
  spatial?: boolean;

  /** Optional category labels for categorical dimensions */
  categories?: string[];

  /** Optional human-readable description for UI tooltips */
  description?: string;
}

/**
 * State object representing the current position and display configuration
 * for navigating through nD points data.
 *
 * This is the core data structure that tracks where we are in the nD space
 * and which dimensions are currently being visualized. The scene-level
 * dimension manager maintains a single instance to ensure consistency
 * across all points in the scene.
 *
 * @interface SimpleDims
 */
export interface SimpleDims {
  /** Total number of dimensions in the dataset */
  ndim: number;

  /**
   * Current position/slice in each dimension.
   * For displayed dimensions, this represents the camera center.
   * For non-displayed dimensions, this is the slice position.
   */
  currentStep: number[];

  /**
   * Indices of dimensions currently displayed in the 3D scene.
   * Maximum of 3 dimensions can be displayed simultaneously (X, Y, Z).
   * Typically the last 3 dimensions for spatial data.
   */
  displayed: number[];

  /** Optional metadata providing semantic information for each dimension */
  metadata?: DimensionMetadata[];
}

/**
 * Initializes a SimpleDims object from points position data.
 *
 * This function creates the initial dimension state for nD visualization,
 * inferring the number of dimensions from the data structure and setting
 * up sensible defaults for display and navigation.
 *
 * Design decisions:
 * - Non-displayed dimensions start at position 0 (minimum) for predictable behavior
 * - Displayed dimensions are chosen from metadata or default to last 3 (spatial)
 * - Maximum of 3 dimensions can be displayed simultaneously
 *
 * @param numPoints - Number of points in the dataset
 * @param totalElements - Total elements in the positions array (numPoints * ndim)
 * @param metadata - Optional metadata describing each dimension's properties
 * @returns Initialized SimpleDims object ready for use
 * @throws Error if the positions array structure is invalid
 *
 * @internal — re-exported from types/index.ts; no production call site outside
 * this module.
 */
export function initializeDims(
  numPoints: number,
  totalElements: number,
  metadata?: DimensionMetadata[]
): SimpleDims {
  // [types.md OOS-5] Defensive guard against negative / non-integer
  // numPoints. The parameter is typed `number` (TypeScript has no
  // "non-negative integer" refinement), so a buggy caller could pass
  // a negative value or a float. The division-by-numPoints +
  // Number.isInteger check below would not catch all negatives
  // (e.g. -6 / -3 = 2 passes Number.isInteger), and downstream
  // `new Array(ndim)` would throw a misleading RangeError far from
  // the actual bug. Catch it here with a clear message.
  if (!Number.isFinite(numPoints) || numPoints < 0 || !Number.isInteger(numPoints)) {
    throw new Error(`Invalid numPoints: ${numPoints} must be a non-negative integer`);
  }

  // Empty point clouds are legitimate: dividing by zero here would yield
  // Infinity, which then fails Number.isInteger with a misleading
  // "0 elements for 0 points" error. Infer ndim from metadata when given,
  // else default to 3 (the common spatial case). `displayed` stays empty —
  // there is nothing to display.
  if (numPoints === 0) {
    const ndim = metadata && metadata.length > 0 ? metadata.length : 3;
    return {
      ndim,
      currentStep: new Array(ndim).fill(0),
      displayed: [],
      metadata: metadata ?? [],
    };
  }

  // Calculate number of dimensions from array size
  const ndim = totalElements / numPoints;

  if (!Number.isInteger(ndim)) {
    throw new Error(`Invalid positions array: ${totalElements} elements for ${numPoints} points`);
  }

  // Pad with defaults and warn so callers see the gap: silently truncating
  // partial metadata sends the dataset to the "no dim marked for display"
  // fallback, where an authoring bug looks like normal behaviour.
  //
  // The inverse case — metadata.length > ndim — would be silently truncated
  // by the `i < effectiveMetadata.length` clamp in the display-determination
  // loop below, hiding authoring bugs the other direction, so it gets the
  // same warning.
  let effectiveMetadata = metadata;
  if (metadata && metadata.length > 0 && metadata.length < ndim) {
    log.warning(
      Modules.DIMS,
      `dims metadata has ${metadata.length} entries but ndim=${ndim}; ` +
        'padding with default dims so the slice navigator works.'
    );
    effectiveMetadata = [...metadata];
    for (let i = metadata.length; i < ndim; i++) {
      effectiveMetadata.push({ name: `dim${i}`, unit: '', scale: 1.0 });
    }
  } else if (metadata && metadata.length > ndim) {
    log.warning(
      Modules.DIMS,
      `dims metadata has ${metadata.length} entries but ndim=${ndim}; ` +
        `extra entries past index ${ndim - 1} will be ignored.`
    );
  }

  // Initialize all dimensions at position 0 (minimum value)
  // This provides predictable behavior for non-displayed dimensions
  const currentStep = new Array(ndim).fill(0);

  // Determine which dimensions to display in the 3D scene
  let displayed: number[];
  if (effectiveMetadata && effectiveMetadata.length > 0) {
    // Respect explicit display preferences from metadata
    displayed = [];
    for (let i = 0; i < ndim && i < effectiveMetadata.length; i++) {
      const shouldDisplay = effectiveMetadata[i].display === true;
      if (shouldDisplay && displayed.length < 3) {
        displayed.push(i);
      }
    }
    // Fallback: if no dimensions marked for display, use spatial convention
    if (displayed.length === 0) {
      displayed =
        ndim <= 3 ? Array.from({ length: ndim }, (_, i) => i) : [ndim - 3, ndim - 2, ndim - 1];
    }
  } else {
    // Default: assume last 3 dimensions are spatial (X, Y, Z)
    // This is the standard convention for scientific datasets
    displayed =
      ndim <= 3 ? Array.from({ length: ndim }, (_, i) => i) : [ndim - 3, ndim - 2, ndim - 1];
  }

  return {
    ndim,
    currentStep,
    displayed,
    metadata: effectiveMetadata,
  };
}

/**
 * Computes the min/max bounds for each dimension from points position data.
 *
 * This function analyzes the actual data values to determine the natural bounds
 * of each dimension, which is essential for:
 * - Setting up appropriate navigation ranges for sliders
 * - Calculating effective radii for nD hypersphere slicing
 * - Determining camera bounds and centering
 *
 * The positions array is structured as: [point0_dim0, point0_dim1, ..., point1_dim0, ...]
 *
 * @param positions - Flattened array of point positions (size: numPoints * ndim)
 * @param ndim - Number of dimensions per point
 * @param numPoints - Total number of points in the dataset
 * @returns Array of [min, max] tuples for each dimension
 *
 * @internal — re-exported from types/index.ts; no production call site outside
 * this module. Note `SceneDimsManager` has a same-named *method* that reads
 * cached ranges off the manager; the `sceneDimsManager.getDimensionRanges()`
 * calls in `ui/`, `core/` and `input/` are that method, not this function.
 */
export function getDimensionRanges(
  positions: Float32Array,
  ndim: number,
  numPoints: number
): Array<[number, number]> {
  const ranges: Array<[number, number]> = [];

  // Empty-dataset fast path. Without this, the [Infinity, -Infinity] init
  // values leak to downstream consumers (camera bounds, slider ranges)
  // which are not robust against unbounded extents. Return [0, 0]
  // placeholders so consumers see a degenerate-but-finite bounding box.
  if (numPoints === 0) {
    for (let d = 0; d < ndim; d++) {
      ranges.push([0, 0]);
    }
    return ranges;
  }

  // Initialize ranges with extreme values for proper min/max calculation
  for (let d = 0; d < ndim; d++) {
    ranges.push([Infinity, -Infinity]);
  }

  // Scan through all points to find actual min/max bounds
  for (let i = 0; i < numPoints; i++) {
    for (let d = 0; d < ndim; d++) {
      const value = positions[i * ndim + d];
      ranges[d][0] = Math.min(ranges[d][0], value);
      ranges[d][1] = Math.max(ranges[d][1], value);
    }
  }

  return ranges;
}
