/**
 * @generated by scripts/gen_format_contract.py — DO NOT EDIT BY HAND.
 * To change the format contract, edit format-contract/contract.yaml, then run `make gen-contract` (or `hatch run gen-contract`);
 * `hatch run check-contract` gates against drift.
 *
 * Generated cross-language format-contract constants (TypeScript side).
 * Single source of truth: format-contract/contract.yaml. This is the
 * consumer half of the Python <-> TypeScript format contract (the writer
 * half is luxar/src/luxar/typing_utils/_format_contract.py).
 */

// --- scene (.luxar.zarr) format version ---
export const SCENE_FORMAT_VERSION = '0.1';
export const SUPPORTED_SCENE_VERSIONS: readonly string[] = ['0.1', '0.2', '0.3'];
export type SceneFormatVersion = '0.1' | '0.2' | '0.3';

// --- standalone gsplats (.gsplats.zarr) node-tree format version ---
export const GSPLATS_FORMAT_VERSION = '3.2';
export const SUPPORTED_GSPLATS_FORMAT_VERSIONS: readonly string[] = ['3.0', '3.1', '3.2'];
export type GSplatsFormatVersion = '3.0' | '3.1' | '3.2';

// --- root-header format_type identifying a standalone gsplats store ---
export const FORMAT_TYPE_GSPLATS = 'gsplats_zarr';

// --- scene-graph node types ---
export const NODE_TYPES: readonly string[] = ['scene', 'group', 'points', 'lines', 'gsplats'];
export type NodeTypeName = 'scene' | 'group' | 'points' | 'lines' | 'gsplats';

// --- specialized-group kinds ---
export const NODE_KINDS: readonly string[] = ['lod', 'partition'];
export type NodeKind = 'lod' | 'partition';

// --- on-disk array encoding scheme names ---
export const ENCODING_NAMES: readonly string[] = [
  'none',
  'broadcasted',
  'array_ref',
  'lut_uint8',
  'lut_uint16',
  'rgb_uint8',
  'rgb_uint16',
  'bounded_scalar_uint8',
  'bounded_scalar_uint16',
  'geolog_scalar_uint8',
  'geolog_scalar_uint16',
  'log_scalar_uint8',
  'log_scalar_uint16',
  'linear_perchannel_u8',
  'linear_perchannel_u16',
  'log_perchannel_u8',
  'log_perchannel_u16',
  'signed_log_perchannel_u8',
  'signed_log_perchannel_u16',
  'geolog_perchannel_u8',
  'geolog_perchannel_u16',
  'float16',
  'float32',
  'uint8',
  'uint16',
  'uint32',
  'uint64',
];
export type EncodingName =
  | 'none'
  | 'broadcasted'
  | 'array_ref'
  | 'lut_uint8'
  | 'lut_uint16'
  | 'rgb_uint8'
  | 'rgb_uint16'
  | 'bounded_scalar_uint8'
  | 'bounded_scalar_uint16'
  | 'geolog_scalar_uint8'
  | 'geolog_scalar_uint16'
  | 'log_scalar_uint8'
  | 'log_scalar_uint16'
  | 'linear_perchannel_u8'
  | 'linear_perchannel_u16'
  | 'log_perchannel_u8'
  | 'log_perchannel_u16'
  | 'signed_log_perchannel_u8'
  | 'signed_log_perchannel_u16'
  | 'geolog_perchannel_u8'
  | 'geolog_perchannel_u16'
  | 'float16'
  | 'float32'
  | 'uint8'
  | 'uint16'
  | 'uint32'
  | 'uint64';

// --- canonical metadata attribute keys ---
export const ATTR_KEYS: readonly string[] = [
  'format_version',
  'format_type',
  'content_hash',
  'display_type',
  'max_elements',
  'position_bounds',
  'kind',
];
export type AttrKey =
  | 'format_version'
  | 'format_type'
  | 'content_hash'
  | 'display_type'
  | 'max_elements'
  | 'position_bounds'
  | 'kind';

// --- canonical gsplats array names ---
export const ARRAY_NAMES: readonly string[] = [
  'centers',
  'amplitudes',
  'cholesky_factors',
  'cholesky_factors_diag',
  'cholesky_factors_offdiag',
  'colors',
];
export type ArrayName =
  | 'centers'
  | 'amplitudes'
  | 'cholesky_factors'
  | 'cholesky_factors_diag'
  | 'cholesky_factors_offdiag'
  | 'colors';
