/**
 * @generated by scripts/gen_format_contract.py — DO NOT EDIT BY HAND.
 * To change the format contract, edit format-contract/contract.yaml, then run `make gen-contract` (or `hatch run gen-contract`);
 * `hatch run check-contract` gates against drift.
 *
 * Generated cross-language format-contract constants (TypeScript side).
 * Single source of truth: format-contract/contract.yaml. This is the
 * consumer half of the Python <-> TypeScript format contract (the writer
 * half is luxar/src/luxar/typing_utils/_format_contract.py).
 */

/**
 * Current `.luxar.zarr` scene format version — the version the Python writer emits and this build treats as current.
 */
export const SCENE_FORMAT_VERSION = '0.1';
/**
 * Scene format versions declared loadable by this build.
 */
export const SUPPORTED_SCENE_VERSIONS: readonly string[] = ['0.1', '0.2', '0.3'];
/**
 * Union of the supported scene format version strings.
 */
export type SceneFormatVersion = '0.1' | '0.2' | '0.3';

/**
 * Current standalone `.gsplats.zarr` node-tree format version — the version the Python writer emits and this build treats as current.
 */
export const GSPLATS_FORMAT_VERSION = '3.4';
/**
 * Standalone gsplats node-tree format versions this build can load; the loader matches a store on-disk format_version against this allowlist.
 */
export const SUPPORTED_GSPLATS_FORMAT_VERSIONS: readonly string[] = [
  '3.0',
  '3.1',
  '3.2',
  '3.3',
  '3.4',
];
/**
 * Union of the supported standalone gsplats format version strings.
 */
export type GSplatsFormatVersion = '3.0' | '3.1' | '3.2' | '3.3' | '3.4';

/**
 * Root-header `format_type` value identifying a standalone gsplats store.
 */
export const FORMAT_TYPE_GSPLATS = 'gsplats_zarr';

/**
 * All scene-graph node type names.
 */
export const NODE_TYPES: readonly NodeTypeName[] = [
  'scene',
  'group',
  'points',
  'lines',
  'gsplats',
  'mesh',
  'sound',
];
/**
 * Union of the scene-graph node type names.
 */
export type NodeTypeName = 'scene' | 'group' | 'points' | 'lines' | 'gsplats' | 'mesh' | 'sound';

/**
 * Leaf geometry types — the element-bearing subset of NODE_TYPES.
 */
export const GEOMETRY_TYPES: readonly GeometryTypeName[] = ['points', 'lines', 'gsplats', 'mesh'];
/**
 * Union of the leaf geometry type names.
 */
export type GeometryTypeName = 'points' | 'lines' | 'gsplats' | 'mesh';

/**
 * Viewer-drawable geometry types: the subset of `GEOMETRY_TYPES` that has a
 * loader, a `GEOMETRY_DESCRIPTORS` row, a `PARTIAL_EXTEND_TOLERANCE` arm and a
 * hidden-dim tolerance arm. A CAPABILITY, not the vocabulary — key dispatch
 * tables on this, not on `GeometryTypeName`, so a not-yet-drawable type cannot
 * resolve to no loader. See contract.yaml::loader_types.
 */
export const LOADER_TYPES: readonly LoaderTypeName[] = ['points', 'lines', 'gsplats', 'mesh'];
/**
 * Union of the viewer-drawable geometry type names.
 */
export type LoaderTypeName = 'points' | 'lines' | 'gsplats' | 'mesh';

/**
 * Specialized-group kinds (lod, partition).
 */
export const NODE_KINDS: readonly NodeKind[] = ['lod', 'partition'];
/**
 * Union of the specialized-group kind names.
 */
export type NodeKind = 'lod' | 'partition';

/**
 * All on-disk array encoding scheme names.
 */
export const ENCODING_NAMES: readonly EncodingName[] = [
  'none',
  'broadcasted',
  'array_ref',
  'lut_uint8',
  'lut_uint16',
  'rgb_uint8',
  'rgb_uint16',
  'bounded_scalar_uint8',
  'bounded_scalar_uint16',
  'geolog_scalar_uint8',
  'geolog_scalar_uint16',
  'log_scalar_uint8',
  'log_scalar_uint16',
  'linear_perchannel_u8',
  'linear_perchannel_u16',
  'log_perchannel_u8',
  'log_perchannel_u16',
  'signed_log_perchannel_u8',
  'signed_log_perchannel_u16',
  'geolog_perchannel_u8',
  'geolog_perchannel_u16',
  'float16',
  'float32',
  'uint8',
  'uint16',
  'uint32',
  'uint64',
];
/**
 * Union of the on-disk array encoding scheme names.
 */
export type EncodingName =
  | 'none'
  | 'broadcasted'
  | 'array_ref'
  | 'lut_uint8'
  | 'lut_uint16'
  | 'rgb_uint8'
  | 'rgb_uint16'
  | 'bounded_scalar_uint8'
  | 'bounded_scalar_uint16'
  | 'geolog_scalar_uint8'
  | 'geolog_scalar_uint16'
  | 'log_scalar_uint8'
  | 'log_scalar_uint16'
  | 'linear_perchannel_u8'
  | 'linear_perchannel_u16'
  | 'log_perchannel_u8'
  | 'log_perchannel_u16'
  | 'signed_log_perchannel_u8'
  | 'signed_log_perchannel_u16'
  | 'geolog_perchannel_u8'
  | 'geolog_perchannel_u16'
  | 'float16'
  | 'float32'
  | 'uint8'
  | 'uint16'
  | 'uint32'
  | 'uint64';

/**
 * Canonical metadata attribute keys.
 */
export const ATTR_KEYS: readonly AttrKey[] = [
  'format_version',
  'format_type',
  'content_hash',
  'display_type',
  'max_elements',
  'position_bounds',
  'kind',
];
/**
 * Union of the canonical metadata attribute key names.
 */
export type AttrKey =
  | 'format_version'
  | 'format_type'
  | 'content_hash'
  | 'display_type'
  | 'max_elements'
  | 'position_bounds'
  | 'kind';

/**
 * Canonical gsplats array names.
 */
export const ARRAY_NAMES: readonly ArrayName[] = [
  'centers',
  'amplitudes',
  'cholesky_factors',
  'cholesky_factors_diag',
  'cholesky_factors_offdiag',
  'colors',
  'label_ids',
];
/**
 * Union of the canonical gsplats array names.
 */
export type ArrayName =
  | 'centers'
  | 'amplitudes'
  | 'cholesky_factors'
  | 'cholesky_factors_diag'
  | 'cholesky_factors_offdiag'
  | 'colors'
  | 'label_ids';
