/**
 * @generated by scripts/gen_format_contract.py — DO NOT EDIT BY HAND.
 * To change the format contract, edit format-contract/contract.yaml, then run `make gen-contract` (or `hatch run gen-contract`);
 * `hatch run check-contract` gates against drift.
 *
 * Generated cross-language format-contract constants (TypeScript side).
 * Single source of truth: format-contract/contract.yaml. This is the
 * consumer half of the Python <-> TypeScript format contract (the writer
 * half is luxar/src/luxar/typing_utils/_format_contract.py).
 */

/**
 * Current `.luxar.zarr` scene format version — the version the Python writer emits and this build treats as current.
 */
export const SCENE_FORMAT_VERSION = '0.2';
/**
 * Scene format versions declared loadable by this build.
 */
export const SUPPORTED_SCENE_VERSIONS: readonly string[] = ['0.1', '0.2'];
/**
 * Union of the supported scene format version strings.
 */
export type SceneFormatVersion = '0.1' | '0.2';

/**
 * Current standalone `.gsplats.zarr` node-tree format version — the version the Python writer emits and this build treats as current.
 */
export const GSPLATS_FORMAT_VERSION = '3.4';
/**
 * Standalone gsplats node-tree format versions this build can load; the loader matches a store on-disk format_version against this allowlist.
 */
export const SUPPORTED_GSPLATS_FORMAT_VERSIONS: readonly string[] = [
  '3.0',
  '3.1',
  '3.2',
  '3.3',
  '3.4',
];
/**
 * Union of the supported standalone gsplats format version strings.
 */
export type GSplatsFormatVersion = '3.0' | '3.1' | '3.2' | '3.3' | '3.4';

/**
 * Root-header `format_type` value identifying a standalone gsplats store.
 */
export const FORMAT_TYPE_GSPLATS = 'gsplats_zarr';

/**
 * Root-header `format_type` value identifying a compiled `.luxar.zarr` scene (format 0.2+).
 */
export const FORMAT_TYPE_SCENE = 'luxar_zarr';

/**
 * The scene 0.1 root-header version key. Readers fall back to it when
 * `format_version` is absent; the writer no longer emits it.
 */
export const LEGACY_SCENE_VERSION_ATTR = 'luxar_version';

/**
 * Root-header attr recording the Luxar SOFTWARE version that wrote a
 * scene. Provenance only — excluded from `content_hash`, so it never
 * invalidates a viewer cache.
 */
export const SOFTWARE_VERSION_ATTR = 'luxar_software_version';

/**
 * The one key a categorical `nd_transform` entry carries; an affine entry
 * carries `ND_TRANSFORM_AFFINE_KEYS` instead (mutually exclusive).
 */
export const ND_TRANSFORM_PERMUTATION_KEY = 'permutation';

/**
 * All scene-graph node type names.
 */
export const NODE_TYPES: readonly NodeTypeName[] = [
  'scene',
  'group',
  'points',
  'lines',
  'gsplats',
  'mesh',
  'sound',
];
/**
 * Union of the scene-graph node type names.
 */
export type NodeTypeName = 'scene' | 'group' | 'points' | 'lines' | 'gsplats' | 'mesh' | 'sound';

/**
 * Leaf geometry types — the element-bearing subset of NODE_TYPES.
 */
export const GEOMETRY_TYPES: readonly GeometryTypeName[] = ['points', 'lines', 'gsplats', 'mesh'];
/**
 * Union of the leaf geometry type names.
 */
export type GeometryTypeName = 'points' | 'lines' | 'gsplats' | 'mesh';

/**
 * Viewer-drawable geometry types: the subset of `GEOMETRY_TYPES` that has a
 * loader, a `GEOMETRY_DESCRIPTORS` row, a `PARTIAL_EXTEND_TOLERANCE` arm and a
 * hidden-dim tolerance arm. A CAPABILITY, not the vocabulary — key dispatch
 * tables on this, not on `GeometryTypeName`, so a not-yet-drawable type cannot
 * resolve to no loader. See contract.yaml::loader_types.
 */
export const LOADER_TYPES: readonly LoaderTypeName[] = ['points', 'lines', 'gsplats', 'mesh'];
/**
 * Union of the viewer-drawable geometry type names.
 */
export type LoaderTypeName = 'points' | 'lines' | 'gsplats' | 'mesh';

/**
 * Specialized-group kinds (lod, partition).
 */
export const NODE_KINDS: readonly NodeKind[] = ['lod', 'partition'];
/**
 * Union of the specialized-group kind names.
 */
export type NodeKind = 'lod' | 'partition';

/**
 * All on-disk array encoding scheme names.
 */
export const ENCODING_NAMES: readonly EncodingName[] = [
  'none',
  'broadcasted',
  'array_ref',
  'lut_uint8',
  'lut_uint16',
  'rgb_uint8',
  'rgb_uint16',
  'bounded_scalar_uint8',
  'bounded_scalar_uint16',
  'geolog_scalar_uint8',
  'geolog_scalar_uint16',
  'log_scalar_uint8',
  'log_scalar_uint16',
  'linear_perchannel_u8',
  'linear_perchannel_u16',
  'log_perchannel_u8',
  'log_perchannel_u16',
  'signed_log_perchannel_u8',
  'signed_log_perchannel_u16',
  'geolog_perchannel_u8',
  'geolog_perchannel_u16',
  'float16',
  'float32',
  'uint8',
  'uint16',
  'uint32',
  'uint64',
];
/**
 * Union of the on-disk array encoding scheme names.
 */
export type EncodingName =
  | 'none'
  | 'broadcasted'
  | 'array_ref'
  | 'lut_uint8'
  | 'lut_uint16'
  | 'rgb_uint8'
  | 'rgb_uint16'
  | 'bounded_scalar_uint8'
  | 'bounded_scalar_uint16'
  | 'geolog_scalar_uint8'
  | 'geolog_scalar_uint16'
  | 'log_scalar_uint8'
  | 'log_scalar_uint16'
  | 'linear_perchannel_u8'
  | 'linear_perchannel_u16'
  | 'log_perchannel_u8'
  | 'log_perchannel_u16'
  | 'signed_log_perchannel_u8'
  | 'signed_log_perchannel_u16'
  | 'geolog_perchannel_u8'
  | 'geolog_perchannel_u16'
  | 'float16'
  | 'float32'
  | 'uint8'
  | 'uint16'
  | 'uint32'
  | 'uint64';

/**
 * Canonical metadata attribute keys.
 */
export const ATTR_KEYS: readonly AttrKey[] = [
  'format_version',
  'format_type',
  'luxar_software_version',
  'type',
  'content_hash',
  'scene_dimensions',
  'display_type',
  'max_elements',
  'position_bounds',
  'kind',
  'selector',
  'default_level',
  'child_index',
];
/**
 * Union of the canonical metadata attribute key names.
 */
export type AttrKey =
  | 'format_version'
  | 'format_type'
  | 'luxar_software_version'
  | 'type'
  | 'content_hash'
  | 'scene_dimensions'
  | 'display_type'
  | 'max_elements'
  | 'position_bounds'
  | 'kind'
  | 'selector'
  | 'default_level'
  | 'child_index';

/**
 * Canonical gsplats array names.
 */
export const ARRAY_NAMES: readonly ArrayName[] = [
  'centers',
  'amplitudes',
  'cholesky_factors',
  'cholesky_factors_diag',
  'cholesky_factors_offdiag',
  'colors',
  'label_ids',
];
/**
 * Union of the canonical gsplats array names.
 */
export type ArrayName =
  | 'centers'
  | 'amplitudes'
  | 'cholesky_factors'
  | 'cholesky_factors_diag'
  | 'cholesky_factors_offdiag'
  | 'colors'
  | 'label_ids';

/**
 * Render / appearance attribute keys a caller may author on at least one
 * node type — the Python writer's typo allowlist. `ComposableAttrs` keys
 * must be a subset.
 */
export const RENDER_ATTR_KEYS: readonly RenderAttrKey[] = [
  'absorption',
  'blending_mode',
  'colormap',
  'gamma',
  'intensity',
  'layer',
  'layer_order',
  'offset',
  'opacity',
  'visible',
  'copy',
  'link',
  'link_target',
  'join',
  'alpha_cutoff',
  'ambient',
  'material',
  'roughness',
  'metalness',
  'clearcoat',
  'clearcoat_roughness',
  'iridescence',
  'sheen',
  'sheen_color',
  'transmission',
  'ior',
  'thickness',
  'attenuation_color',
  'attenuation_distance',
  'dispersion',
  'refract_data',
  'shade_exponent',
  'shininess',
  'specular',
  'texture_filter',
  'texture_wrap',
  'slab_tolerance',
];
/**
 * Union of the render / appearance attribute key names.
 */
export type RenderAttrKey =
  | 'absorption'
  | 'blending_mode'
  | 'colormap'
  | 'gamma'
  | 'intensity'
  | 'layer'
  | 'layer_order'
  | 'offset'
  | 'opacity'
  | 'visible'
  | 'copy'
  | 'link'
  | 'link_target'
  | 'join'
  | 'alpha_cutoff'
  | 'ambient'
  | 'material'
  | 'roughness'
  | 'metalness'
  | 'clearcoat'
  | 'clearcoat_roughness'
  | 'iridescence'
  | 'sheen'
  | 'sheen_color'
  | 'transmission'
  | 'ior'
  | 'thickness'
  | 'attenuation_color'
  | 'attenuation_distance'
  | 'dispersion'
  | 'refract_data'
  | 'shade_exponent'
  | 'shininess'
  | 'specular'
  | 'texture_filter'
  | 'texture_wrap'
  | 'slab_tolerance';

/**
 * `selector` values a kind=lod group may carry — the units of its
 * children's `coverage_fraction` thresholds.
 */
export const LOD_SELECTORS: readonly LodSelectorName[] = ['coverage', 'screen-area'];
/**
 * Union of the kind=lod `selector` attr values.
 */
export type LodSelectorName = 'coverage' | 'screen-area';

/**
 * The canonical `blending_mode` values, in panel-dropdown order.
 */
export const BLENDING_MODES: readonly BlendingModeName[] = [
  'additive',
  'volumetric',
  'normal',
  'max',
  'opaque',
  'luminous',
];
/**
 * Union of the canonical `blending_mode` values.
 */
export type BlendingModeName = 'additive' | 'volumetric' | 'normal' | 'max' | 'opaque' | 'luminous';

/**
 * Tone-mapping operator names a `viewer_config.tone_mapping` may carry.
 */
export const TONE_MAPPINGS: readonly ToneMappingName[] = [
  'None',
  'Linear',
  'Reinhard',
  'Cineon',
  'ACES',
  'AgX',
  'Neutral',
];
/**
 * Union of the tone-mapping operator names.
 */
export type ToneMappingName =
  'None' | 'Linear' | 'Reinhard' | 'Cineon' | 'ACES' | 'AgX' | 'Neutral';

/**
 * Built-in colormap names a `colormap` attr may carry (the `'custom'`
 * sentinel is not a name). Must equal the keys of
 * `rendering/colormap-data.ts::BUILTIN_COLORMAPS`.
 */
export const BUILTIN_COLORMAP_NAMES: readonly BuiltinColormapName[] = [
  'green',
  'magenta',
  'cyan',
  'red',
  'blue',
  'yellow',
  'gray',
  'orange',
  'bop_blue',
  'bop_orange',
  'bop_purple',
  'viridis',
  'inferno',
  'plasma',
  'turbo',
  'fire',
  'ice',
  'phase',
  'RdBu',
  'coolwarm',
];
/**
 * Union of the built-in colormap names.
 */
export type BuiltinColormapName =
  | 'green'
  | 'magenta'
  | 'cyan'
  | 'red'
  | 'blue'
  | 'yellow'
  | 'gray'
  | 'orange'
  | 'bop_blue'
  | 'bop_orange'
  | 'bop_purple'
  | 'viridis'
  | 'inferno'
  | 'plasma'
  | 'turbo'
  | 'fire'
  | 'ice'
  | 'phase'
  | 'RdBu'
  | 'coolwarm';

/**
 * Canonical dimension `unit` spellings on disk (the Python `PhysicalUnit`
 * enum). Input aliases such as `meter` never reach the store.
 */
export const PHYSICAL_UNITS: readonly PhysicalUnitName[] = [
  'nm',
  'um',
  'mm',
  'cm',
  'm',
  'metre',
  'km',
  'inch',
  'foot',
  'px',
  's',
  'au',
];
/**
 * Union of the canonical physical-unit spellings.
 */
export type PhysicalUnitName =
  'nm' | 'um' | 'mm' | 'cm' | 'm' | 'metre' | 'km' | 'inch' | 'foot' | 'px' | 's' | 'au';

/**
 * `ordering` attr values: how a geometry node's elements were spatially
 * sorted (`none` = not reordered).
 */
export const ORDERING_METHODS: readonly OrderingMethodName[] = ['morton', 'hilbert', 'none'];
/**
 * Union of the `ordering` attr values.
 */
export type OrderingMethodName = 'morton' | 'hilbert' | 'none';

/**
 * Lines-only `join` attr values (joint strategy at a degree-2 joint).
 */
export const LINE_JOIN_STYLES: readonly LineJoinStyleName[] = ['none', 'miter'];
/**
 * Union of the line join style names.
 */
export type LineJoinStyleName = 'none' | 'miter';

/**
 * `line_type` attr values: how a lines node's vertices + segments are read.
 */
export const LINE_TYPES: readonly LineTypeName[] = ['segments', 'polyline', 'loop', 'indexed'];
/**
 * Union of the `line_type` attr values.
 */
export type LineTypeName = 'segments' | 'polyline' | 'loop' | 'indexed';

/**
 * Keys an affine `nd_transform` entry may carry; a categorical entry
 * carries `ND_TRANSFORM_PERMUTATION_KEY` instead.
 */
export const ND_TRANSFORM_AFFINE_KEYS: readonly NdTransformAffineKey[] = ['scale', 'offset'];
/**
 * Union of the affine `nd_transform` entry keys.
 */
export type NdTransformAffineKey = 'scale' | 'offset';

/**
 * Keys of one entry in the root `scene_dimensions.dimensions[]` list
 * (`SceneDimensionAttrs` is checked against this at the type level).
 */
export const DIMENSION_ATTR_KEYS: readonly DimensionAttrKey[] = [
  'name',
  'unit',
  'range',
  'step',
  'display',
  'discrete',
  'cyclic',
  'scale',
  'spatial',
  'description',
  'categories',
];
/**
 * Union of the per-dimension attr keys.
 */
export type DimensionAttrKey =
  | 'name'
  | 'unit'
  | 'range'
  | 'step'
  | 'display'
  | 'discrete'
  | 'cyclic'
  | 'scale'
  | 'spatial'
  | 'description'
  | 'categories';
