"""Type definitions for Luxar.

This package is organized as follows:
- aliases.py: Simple type aliases for readability
- protocols.py: Protocols, dataclasses, validation functions, and type guards
- enums.py: Enumeration types
- constants.py: Constant values
- config.py: Configuration classes
"""

# Re-export everything for backward compatibility
# Import validation functions from validation.types module
from ..validation.types import (
    is_color_array,
    is_position_array,
    is_transform_matrix,
    validate_blending_mode,
    validate_colors,
    validate_gamma,
    validate_node_type,
    validate_opacity,
    validate_physical_unit,
    validate_positions,
    validate_radii,
    validate_sharpness,
    validate_transform,
)
from .aliases import (
    ArrayLike,
    ChunkSpec,
    ColorArray,
    ColorRGB,
    ColorRGBA,
    ColorValue,
    DimensionIndex,
    DimensionIndices,
    DimensionRange,
    Float32Array,
    GroupAttrs,
    MaxShape,
    NodeAttributes,
    NodePath,
    PathLike,
    PointsMetadata,
    PositionArray,
    RadiusArray,
    SceneHierarchy,
    SceneMetadata,
    SharpnessArray,
    TransformList,
    TransformMatrix,
    Uint8Array,
    ValidationResult,
    ZarrAttrs,
)
from .constants import (
    DEFAULT_BLENDING_MODE,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_COMPRESSOR,
    DEFAULT_GAMMA,
    DEFAULT_OPACITY,
    DEFAULT_ZARR_VERSION,
    GAMMA_MAX,
    GAMMA_MIN,
    MAX_POINT_RADIUS,
    MIN_POINT_RADIUS,
    OPACITY_MAX,
    OPACITY_MIN,
)
from .enums import BlendingMode, Defaults, NodeType, PhysicalUnit, RenderingLimits
from .protocols import (
    CompressorProtocol,
    NodeProtocol,
    NodeT,
    NumericT,
    PointsProtocol,
    SceneProtocol,
    ZarrDataT,
)

__all__ = [
    # From aliases
    "ArrayLike",
    "ChunkSpec",
    "ColorArray",
    "ColorRGB",
    "ColorRGBA",
    "ColorValue",
    "DimensionIndex",
    "DimensionIndices",
    "DimensionRange",
    "Float32Array",
    "GroupAttrs",
    "MaxShape",
    "NodeAttributes",
    "NodePath",
    "PathLike",
    "PointsMetadata",
    "PositionArray",
    "RadiusArray",
    "SceneHierarchy",
    "SceneMetadata",
    "SharpnessArray",
    "TransformList",
    "TransformMatrix",
    "Uint8Array",
    "ValidationResult",
    "ZarrAttrs",
    # From protocols
    "CompressorProtocol",
    "NodeProtocol",
    "NodeT",
    "NumericT",
    "PointsProtocol",
    "SceneProtocol",
    "ZarrDataT",
    "is_color_array",
    "is_position_array",
    "is_transform_matrix",
    "validate_blending_mode",
    "validate_colors",
    "validate_gamma",
    "validate_node_type",
    "validate_opacity",
    "validate_physical_unit",
    "validate_positions",
    "validate_radii",
    "validate_sharpness",
    "validate_transform",
    # From enums
    "BlendingMode",
    "NodeType",
    "PhysicalUnit",
    # From constants
    "DEFAULT_BLENDING_MODE",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_COMPRESSOR",
    "DEFAULT_GAMMA",
    "DEFAULT_OPACITY",
    "DEFAULT_ZARR_VERSION",
    "GAMMA_MAX",
    "GAMMA_MIN",
    "MAX_POINT_RADIUS",
    "MIN_POINT_RADIUS",
    "OPACITY_MAX",
    "OPACITY_MIN",
    # From config
    "Defaults",
    "RenderingLimits",
]
