# @generated by scripts/gen_format_contract.py — DO NOT EDIT BY HAND.
# To change the format contract, edit format-contract/contract.yaml, then run `make gen-contract` (or `hatch run gen-contract`);
# `hatch run check-contract` gates against drift.
"""Generated cross-language format-contract constants (Python side).

Single source of truth: ``format-contract/contract.yaml``. This module is a
mechanical projection of it — the writer half of the Python <-> TypeScript
format contract (the TS half is ``luxar-viewer/src/types/format-contract.ts``).
"""

from __future__ import annotations

from typing import Final, Literal

# --- scene (.luxar.zarr) format version ---
SceneFormatVersion = Literal["0.1", "0.2", "0.3"]
SCENE_FORMAT_VERSION: Final[SceneFormatVersion] = "0.1"
SUPPORTED_SCENE_VERSIONS: Final[tuple[SceneFormatVersion, ...]] = ("0.1", "0.2", "0.3")

# --- standalone gsplats (.gsplats.zarr) node-tree format version ---
GSplatsFormatVersion = Literal["3.0", "3.1", "3.2", "3.3"]
GSPLATS_FORMAT_VERSION: Final[GSplatsFormatVersion] = "3.3"
SUPPORTED_GSPLATS_VERSIONS: Final[tuple[GSplatsFormatVersion, ...]] = (
    "3.0",
    "3.1",
    "3.2",
    "3.3",
)

# --- root-header format_type identifying a standalone gsplats store ---
FORMAT_TYPE_GSPLATS: Final[str] = "gsplats_zarr"

# --- scene-graph node types ---
NodeTypeName = Literal["scene", "group", "points", "lines", "gsplats"]
NODE_TYPES: Final[tuple[NodeTypeName, ...]] = (
    "scene",
    "group",
    "points",
    "lines",
    "gsplats",
)

# --- leaf geometry types (the element-bearing subset of NODE_TYPES) ---
GeometryTypeName = Literal["points", "lines", "gsplats"]
GEOMETRY_TYPES: Final[tuple[GeometryTypeName, ...]] = ("points", "lines", "gsplats")

# --- specialized-group kinds ---
NodeKind = Literal["lod", "partition"]
NODE_KINDS: Final[tuple[NodeKind, ...]] = ("lod", "partition")

# --- on-disk array encoding scheme names ---
EncodingName = Literal[
    "none",
    "broadcasted",
    "array_ref",
    "lut_uint8",
    "lut_uint16",
    "rgb_uint8",
    "rgb_uint16",
    "bounded_scalar_uint8",
    "bounded_scalar_uint16",
    "geolog_scalar_uint8",
    "geolog_scalar_uint16",
    "log_scalar_uint8",
    "log_scalar_uint16",
    "linear_perchannel_u8",
    "linear_perchannel_u16",
    "log_perchannel_u8",
    "log_perchannel_u16",
    "signed_log_perchannel_u8",
    "signed_log_perchannel_u16",
    "geolog_perchannel_u8",
    "geolog_perchannel_u16",
    "float16",
    "float32",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
]
ENCODING_NAMES: Final[tuple[EncodingName, ...]] = (
    "none",
    "broadcasted",
    "array_ref",
    "lut_uint8",
    "lut_uint16",
    "rgb_uint8",
    "rgb_uint16",
    "bounded_scalar_uint8",
    "bounded_scalar_uint16",
    "geolog_scalar_uint8",
    "geolog_scalar_uint16",
    "log_scalar_uint8",
    "log_scalar_uint16",
    "linear_perchannel_u8",
    "linear_perchannel_u16",
    "log_perchannel_u8",
    "log_perchannel_u16",
    "signed_log_perchannel_u8",
    "signed_log_perchannel_u16",
    "geolog_perchannel_u8",
    "geolog_perchannel_u16",
    "float16",
    "float32",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
)

# --- canonical metadata attribute keys ---
AttrKey = Literal[
    "format_version",
    "format_type",
    "content_hash",
    "display_type",
    "max_elements",
    "position_bounds",
    "kind",
]
ATTR_KEYS: Final[tuple[AttrKey, ...]] = (
    "format_version",
    "format_type",
    "content_hash",
    "display_type",
    "max_elements",
    "position_bounds",
    "kind",
)

# --- canonical gsplats array names ---
ArrayName = Literal[
    "centers",
    "amplitudes",
    "cholesky_factors",
    "cholesky_factors_diag",
    "cholesky_factors_offdiag",
    "colors",
]
ARRAY_NAMES: Final[tuple[ArrayName, ...]] = (
    "centers",
    "amplitudes",
    "cholesky_factors",
    "cholesky_factors_diag",
    "cholesky_factors_offdiag",
    "colors",
)

__all__ = [
    "SceneFormatVersion",
    "SCENE_FORMAT_VERSION",
    "SUPPORTED_SCENE_VERSIONS",
    "GSplatsFormatVersion",
    "GSPLATS_FORMAT_VERSION",
    "SUPPORTED_GSPLATS_VERSIONS",
    "FORMAT_TYPE_GSPLATS",
    "NodeTypeName",
    "NODE_TYPES",
    "NodeKind",
    "NODE_KINDS",
    "EncodingName",
    "ENCODING_NAMES",
    "AttrKey",
    "ATTR_KEYS",
    "ArrayName",
    "ARRAY_NAMES",
]
